{"created": 1758736407.834471, "duration": 49.323591232299805, "exitcode": 1, "root": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant", "environment": {}, "summary": {"passed": 46, "failed": 10, "total": 56, "collected": 56}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/__init__.py", "type": "Package"}]}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "type": "Function", "lineno": 130}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "type": "Function", "lineno": 136}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "type": "Function", "lineno": 143}]}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "type": "Function", "lineno": 165}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "type": "Function", "lineno": 170}]}, {"nodeid": "tests/test_conversation_flows.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "type": "Class"}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "type": "Class"}]}, {"nodeid": "tests/test_debug.py", "outcome": "passed", "result": [{"nodeid": "tests/test_debug.py::test_python_version", "type": "Function", "lineno": 9}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "type": "Function", "lineno": 14}, {"nodeid": "tests/test_debug.py::test_project_structure", "type": "Function", "lineno": 28}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "type": "Function", "lineno": 48}, {"nodeid": "tests/test_debug.py::test_check_requirements", "type": "Function", "lineno": 84}]}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "type": "Function", "lineno": 77}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "type": "Function", "lineno": 192}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "type": "Function", "lineno": 211}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "type": "Function", "lineno": 224}]}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "type": "Function", "lineno": 281}]}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "type": "Function", "lineno": 311}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "type": "Function", "lineno": 327}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "type": "Function", "lineno": 341}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "type": "Function", "lineno": 358}]}, {"nodeid": "tests/test_phase1_registration.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "type": "Function", "lineno": 47}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "type": "Function", "lineno": 75}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "type": "Function", "lineno": 100}]}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "type": "Function", "lineno": 140}]}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "type": "Function", "lineno": 188}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "type": "Function", "lineno": 220}]}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "type": "Function", "lineno": 253}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "type": "Function", "lineno": 270}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "type": "Function", "lineno": 286}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "type": "Function", "lineno": 300}]}, {"nodeid": "tests/test_phase2_client_management.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "type": "Function", "lineno": 53}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "type": "Function", "lineno": 110}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "type": "Function", "lineno": 144}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "type": "Function", "lineno": 169}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "type": "Function", "lineno": 223}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "type": "Function", "lineno": 248}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "type": "Function", "lineno": 283}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "type": "Function", "lineno": 313}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_phase3_scheduling.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "type": "Class"}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "type": "Function", "lineno": 227}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "type": "Function", "lineno": 242}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "type": "Function", "lineno": 269}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "type": "Function", "lineno": 278}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "type": "Function", "lineno": 286}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "type": "Function", "lineno": 299}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "type": "Function", "lineno": 308}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "type": "Function", "lineno": 317}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "type": "Function", "lineno": 347}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "type": "Function", "lineno": 360}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "type": "Function", "lineno": 369}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "type": "Function", "lineno": 381}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "type": "Function", "lineno": 390}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "type": "Function", "lineno": 403}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "type": "Function", "lineno": 412}]}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "type": "Function", "lineno": 433}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "type": "Function", "lineno": 457}]}, {"nodeid": "tests/test_refiloe_complete.py", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "type": "Class"}]}, {"nodeid": "tests/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py", "type": "Module"}, {"nodeid": "tests/test_debug.py", "type": "Module"}, {"nodeid": "tests/test_phase1_registration.py", "type": "Module"}, {"nodeid": "tests/test_phase2_client_management.py", "type": "Module"}, {"nodeid": "tests/test_phase3_scheduling.py", "type": "Module"}, {"nodeid": "tests/test_refiloe_complete.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "lineno": 130, "outcome": "passed", "keywords": ["test_imports_work", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004840480000041225, "outcome": "passed"}, "call": {"duration": 0.03252004900001282, "outcome": "passed"}, "teardown": {"duration": 1.9234855189999962, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "lineno": 136, "outcome": "passed", "keywords": ["test_mock_message", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003689819999976862, "outcome": "passed"}, "call": {"duration": 0.02213940300001127, "outcome": "passed"}, "teardown": {"duration": 0.9762372210000052, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "lineno": 143, "outcome": "passed", "keywords": ["test_trainer_registration_mock", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00032176400000594185, "outcome": "passed"}, "call": {"duration": 0.022214735999995128, "outcome": "passed"}, "teardown": {"duration": 1.3582972920000032, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "lineno": 165, "outcome": "passed", "keywords": ["test_basic_setup", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023085885000000417, "outcome": "passed"}, "call": {"duration": 9.912600000916427e-05, "outcome": "passed"}, "teardown": {"duration": 1.3156371820000032, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "lineno": 170, "outcome": "passed", "keywords": ["test_mock_registration_flow", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022151409000002786, "outcome": "passed"}, "call": {"duration": 0.00019995499999936328, "outcome": "passed"}, "teardown": {"duration": 1.2368011140000021, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_python_version", "lineno": 9, "outcome": "passed", "keywords": ["test_python_version", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002931990000121232, "outcome": "passed"}, "call": {"duration": 9.457800000234329e-05, "outcome": "passed"}, "teardown": {"duration": 0.9299605209999982, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "lineno": 14, "outcome": "passed", "keywords": ["test_can_import_basic_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002971770000073093, "outcome": "passed"}, "call": {"duration": 8.808500000156982e-05, "outcome": "passed"}, "teardown": {"duration": 1.030351675999995, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_project_structure", "lineno": 28, "outcome": "passed", "keywords": ["test_project_structure", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031609300000923213, "outcome": "passed"}, "call": {"duration": 0.00023994000000016058, "outcome": "passed"}, "teardown": {"duration": 0.9328710190000038, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "lineno": 48, "outcome": "passed", "keywords": ["test_can_import_refiloe_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029766800000174953, "outcome": "passed"}, "call": {"duration": 0.00044663799999966614, "outcome": "passed"}, "teardown": {"duration": 0.5932715539999975, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_check_requirements", "lineno": 84, "outcome": "passed", "keywords": ["test_check_requirements", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003094299999872874, "outcome": "passed"}, "call": {"duration": 0.07645067699999686, "outcome": "passed"}, "teardown": {"duration": 0.9368501170000059, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "lineno": 77, "outcome": "passed", "keywords": ["test_complete_trainer_registration_flow", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0011032299999840234, "outcome": "passed"}, "call": {"duration": 0.06992430699997954, "outcome": "passed"}, "teardown": {"duration": 0.9260537929999941, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "lineno": 192, "outcome": "passed", "keywords": ["test_currency_parsing_variations", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0008052510000027269, "outcome": "passed"}, "call": {"duration": 0.0001430279999965478, "outcome": "passed"}, "teardown": {"duration": 1.0727292219999924, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "lineno": 211, "outcome": "passed", "keywords": ["test_registration_with_missing_fields", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.002925798999996232, "outcome": "passed"}, "call": {"duration": 0.005295114000006151, "outcome": "passed"}, "teardown": {"duration": 0.7216703539999969, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "lineno": 224, "outcome": "failed", "keywords": ["test_trainer_recognition_after_registration", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0008018440000228111, "outcome": "passed"}, "call": {"duration": 0.8330593649999969, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 253, "message": "AssertionError: assert ('john' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> or 'welcome' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'>)\n +  where <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'>()\n +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>.lower\n +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'> = <built-in method get of dict object at 0x7fbfc5018ac0>('response', '')\n +        where <built-in method get of dict object at 0x7fbfc5018ac0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\n +  and   <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'>()\n +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>.lower\n +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'> = <built-in method get of dict object at 0x7fbfc5018ac0>('response', '')\n +        where <built-in method get of dict object at 0x7fbfc5018ac0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 253, "message": "in test_trainer_recognition_after_registration"}], "log": [{"name": "refiloe", "msg": "Background scheduler started", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736374.0010033, "msecs": 1.0, "relativeCreated": 16099.323987960815, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Routes setup complete", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736374.0019746, "msecs": 1.0, "relativeCreated": 16100.295305252075, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736374.0205216, "msecs": 20.0, "relativeCreated": 16118.842363357544, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase1_registration.py:253: in test_trainer_recognition_after_registration\n    assert 'john' in response.get('response', '').lower() or \\\nE   AssertionError: assert ('john' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> or 'welcome' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'>)\nE    +  where <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'>()\nE    +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>.lower\nE    +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'> = <built-in method get of dict object at 0x7fbfc5018ac0>('response', '')\nE    +        where <built-in method get of dict object at 0x7fbfc5018ac0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\nE    +  and   <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='140461602261072'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'>()\nE    +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='140461602254928'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>.lower\nE    +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'> = <built-in method get of dict object at 0x7fbfc5018ac0>('response', '')\nE    +        where <built-in method get of dict object at 0x7fbfc5018ac0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "teardown": {"duration": 0.5528239909999968, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "lineno": 281, "outcome": "failed", "keywords": ["test_client_receives_welcome_after_registration", "TestClientRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0041413290000207326, "outcome": "passed"}, "call": {"duration": 0.0031077000000152566, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 297, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7fbfc3f34180>('success')\n +    where <built-in method get of dict object at 0x7fbfc3f34180> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 297, "message": "in test_client_receives_welcome_after_registration"}], "log": [{"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736374.6593044, "msecs": 659.0, "relativeCreated": 16757.625102996826, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736374.6614568, "msecs": 661.0, "relativeCreated": 16759.777545928955, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase1_registration.py:297: in test_client_receives_welcome_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7fbfc3f34180>('success')\nE    +    where <built-in method get of dict object at 0x7fbfc3f34180> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 0.955258391000001, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "lineno": 311, "outcome": "passed", "keywords": ["test_duplicate_registration_attempt", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006331079999881695, "outcome": "passed"}, "call": {"duration": 0.003455110999993849, "outcome": "passed"}, "teardown": {"duration": 0.5246447350000096, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "lineno": 327, "outcome": "passed", "keywords": ["test_invalid_email_format", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006313050000130715, "outcome": "passed"}, "call": {"duration": 0.00026257199999690783, "outcome": "passed"}, "teardown": {"duration": 0.5499210559999881, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "lineno": 341, "outcome": "passed", "keywords": ["test_extremely_long_input", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006566520000035325, "outcome": "passed"}, "call": {"duration": 9.155199998645003e-05, "outcome": "passed"}, "teardown": {"duration": 0.9561369550000052, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "lineno": 358, "outcome": "passed", "keywords": ["test_special_characters_in_name", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000612669999981108, "outcome": "passed"}, "call": {"duration": 9.325499999590647e-05, "outcome": "passed"}, "teardown": {"duration": 1.0377450160000024, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "lineno": 47, "outcome": "passed", "keywords": ["test_add_client_command_variations", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02300475500001653, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736378.7221797, "msecs": 722.0, "relativeCreated": 20820.500373840332, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.017462848999997505, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7230904, "msecs": 723.0, "relativeCreated": 20821.4111328125, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7299995, "msecs": 729.0, "relativeCreated": 20828.320264816284, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7308981, "msecs": 730.0, "relativeCreated": 20829.218864440918, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7312486, "msecs": 731.0, "relativeCreated": 20829.569339752197, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7314043, "msecs": 731.0, "relativeCreated": 20829.72502708435, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.731908, "msecs": 731.0, "relativeCreated": 20830.228805541992, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7322314, "msecs": 732.0, "relativeCreated": 20830.552101135254, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7323875, "msecs": 732.0, "relativeCreated": 20830.708265304565, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7328978, "msecs": 732.0, "relativeCreated": 20831.218481063843, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.733256, "msecs": 733.0, "relativeCreated": 20831.576824188232, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7334175, "msecs": 733.0, "relativeCreated": 20831.738233566284, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7338834, "msecs": 733.0, "relativeCreated": 20832.20410346985, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7342544, "msecs": 734.0, "relativeCreated": 20832.57508277893, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7344284, "msecs": 734.0, "relativeCreated": 20832.749128341675, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7348902, "msecs": 734.0, "relativeCreated": 20833.210945129395, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7352498, "msecs": 735.0, "relativeCreated": 20833.57048034668, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7354083, "msecs": 735.0, "relativeCreated": 20833.729028701782, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.735884, "msecs": 735.0, "relativeCreated": 20834.20467376709, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.736226, "msecs": 736.0, "relativeCreated": 20834.5468044281, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.736406, "msecs": 736.0, "relativeCreated": 20834.726810455322, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.736911, "msecs": 736.0, "relativeCreated": 20835.23178100586, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7372358, "msecs": 737.0, "relativeCreated": 20835.556507110596, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7373989, "msecs": 737.0, "relativeCreated": 20835.7195854187, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7378647, "msecs": 737.0, "relativeCreated": 20836.185455322266, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7381887, "msecs": 738.0, "relativeCreated": 20836.509466171265, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7383492, "msecs": 738.0, "relativeCreated": 20836.669921875, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7388191, "msecs": 738.0, "relativeCreated": 20837.13984489441, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.739133, "msecs": 739.0, "relativeCreated": 20837.453603744507, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.73929, "msecs": 739.0, "relativeCreated": 20837.610721588135, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736378.7397363, "msecs": 739.0, "relativeCreated": 20838.057041168213, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.8839170249999881, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "lineno": 75, "outcome": "passed", "keywords": ["test_phone_number_normalization", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02280626399999619, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736379.6471262, "msecs": 647.0, "relativeCreated": 21745.446920394897, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.00019397299999468487, "outcome": "passed"}, "teardown": {"duration": 0.9053403690000152, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "lineno": 100, "outcome": "passed", "keywords": ["test_add_client_with_special_names", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02286049299999604, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736380.5761995, "msecs": 576.0, "relativeCreated": 22674.520254135132, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.013125872999978583, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5770917, "msecs": 577.0, "relativeCreated": 22675.41241645813, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5778117, "msecs": 577.0, "relativeCreated": 22676.132440567017, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.578448, "msecs": 578.0, "relativeCreated": 22676.76877975464, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5787642, "msecs": 578.0, "relativeCreated": 22677.084922790527, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5789242, "msecs": 578.0, "relativeCreated": 22677.244901657104, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5794263, "msecs": 579.0, "relativeCreated": 22677.747011184692, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.579732, "msecs": 579.0, "relativeCreated": 22678.0526638031, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5798938, "msecs": 579.0, "relativeCreated": 22678.21455001831, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5854845, "msecs": 585.0, "relativeCreated": 22683.805227279663, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5858178, "msecs": 585.0, "relativeCreated": 22684.138536453247, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.585979, "msecs": 585.0, "relativeCreated": 22684.29970741272, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5864458, "msecs": 586.0, "relativeCreated": 22684.7665309906, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5867815, "msecs": 586.0, "relativeCreated": 22685.102224349976, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.58698, "msecs": 586.0, "relativeCreated": 22685.300827026367, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5874698, "msecs": 587.0, "relativeCreated": 22685.79053878784, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5877798, "msecs": 587.0, "relativeCreated": 22686.100482940674, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.587957, "msecs": 587.0, "relativeCreated": 22686.277627944946, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5884454, "msecs": 588.0, "relativeCreated": 22686.766147613525, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5887516, "msecs": 588.0, "relativeCreated": 22687.07227706909, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5889084, "msecs": 588.0, "relativeCreated": 22687.22915649414, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736380.5894032, "msecs": 589.0, "relativeCreated": 22687.723875045776, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.5159330520000083, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "lineno": 140, "outcome": "failed", "keywords": ["test_view_clients_commands", "TestViewClientsReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000918542999983174, "outcome": "passed"}, "call": {"duration": 0.0050109299999974155, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 160, "message": "AssertionError: Failed to list clients with command: Show my clients\nassert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 160, "message": "in test_view_clients_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.1102388, "msecs": 110.0, "relativeCreated": 23208.55951309204, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.1108494, "msecs": 110.0, "relativeCreated": 23209.17010307312, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.1118057, "msecs": 111.0, "relativeCreated": 23210.126399993896, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase2_client_management.py:160: in test_view_clients_commands\n    assert 'sarah' in message or 'john' in message or 'mike' in message or \\\nE   AssertionError: Failed to list clients with command: Show my clients\nE   assert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "teardown": {"duration": 0.5373556030000088, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "lineno": 188, "outcome": "passed", "keywords": ["test_set_custom_pricing_variations", "critical", "pytestmark", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0014024000000176784, "outcome": "passed"}, "call": {"duration": 0.011987108999989005, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6588924, "msecs": 658.0, "relativeCreated": 23757.21311569214, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.659573, "msecs": 659.0, "relativeCreated": 23757.893800735474, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6604588, "msecs": 660.0, "relativeCreated": 23758.779525756836, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.660786, "msecs": 660.0, "relativeCreated": 23759.106636047363, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6609764, "msecs": 660.0, "relativeCreated": 23759.297132492065, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6614552, "msecs": 661.0, "relativeCreated": 23759.7758769989, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6617594, "msecs": 661.0, "relativeCreated": 23760.080099105835, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6619253, "msecs": 661.0, "relativeCreated": 23760.24603843689, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.66237, "msecs": 662.0, "relativeCreated": 23760.690689086914, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6626778, "msecs": 662.0, "relativeCreated": 23760.998487472534, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6628232, "msecs": 662.0, "relativeCreated": 23761.143922805786, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.663777, "msecs": 663.0, "relativeCreated": 23762.09783554077, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.664102, "msecs": 664.0, "relativeCreated": 23762.422800064087, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6642568, "msecs": 664.0, "relativeCreated": 23762.577533721924, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6647222, "msecs": 664.0, "relativeCreated": 23763.04292678833, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6650221, "msecs": 665.0, "relativeCreated": 23763.34285736084, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6652064, "msecs": 665.0, "relativeCreated": 23763.527154922485, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6656797, "msecs": 665.0, "relativeCreated": 23764.000415802002, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6660268, "msecs": 666.0, "relativeCreated": 23764.347553253174, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6662052, "msecs": 666.0, "relativeCreated": 23764.52589035034, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6666594, "msecs": 666.0, "relativeCreated": 23764.98007774353, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.666985, "msecs": 666.0, "relativeCreated": 23765.305757522583, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6671767, "msecs": 667.0, "relativeCreated": 23765.49744606018, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736381.6676407, "msecs": 667.0, "relativeCreated": 23765.961408615112, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 1.0901533800000038, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "lineno": 220, "outcome": "failed", "keywords": ["test_check_client_pricing", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0013753300000018953, "outcome": "passed"}, "call": {"duration": 0.0025461470000038844, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 239, "message": "AssertionError: Failed to show pricing with: What is Sarah's rate?\nassert ('r' in '' or 'rand' in '' or False)\n +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7fbfc4fb7ae0>)"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 239, "message": "in test_check_client_pricing"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736382.7605999, "msecs": 760.0, "relativeCreated": 24858.920574188232, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736382.7612324, "msecs": 761.0, "relativeCreated": 24859.55309867859, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736382.7622392, "msecs": 762.0, "relativeCreated": 24860.559940338135, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase2_client_management.py:239: in test_check_client_pricing\n    assert 'r' in message or 'rand' in message or \\\nE   AssertionError: Failed to show pricing with: What is Sarah's rate?\nE   assert ('r' in '' or 'rand' in '' or False)\nE    +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7fbfc4fb7ae0>)"}, "teardown": {"duration": 0.9109407920000194, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "lineno": 253, "outcome": "failed", "keywords": ["test_add_client_with_duplicate_phone", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005843559999902936, "outcome": "passed"}, "call": {"duration": 0.008658572999991065, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 268, "message": "AssertionError: assert ('already' in '' or 'exists' in '')\n +  where '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\n +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fbfc3bb7100>('message', '')\n +        where <built-in method get of dict object at 0x7fbfc3bb7100> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\n +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fbfc3bb7100>('message', '')\n +        where <built-in method get of dict object at 0x7fbfc3bb7100> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 268, "message": "in test_add_client_with_duplicate_phone"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736383.6812592, "msecs": 681.0, "relativeCreated": 25779.579877853394, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736383.6856208, "msecs": 685.0, "relativeCreated": 25783.941507339478, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736383.6872551, "msecs": 687.0, "relativeCreated": 25785.57586669922, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase2_client_management.py:268: in test_add_client_with_duplicate_phone\n    assert 'already' in response.get('message', '').lower() or \\\nE   AssertionError: assert ('already' in '' or 'exists' in '')\nE    +  where '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\nE    +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fbfc3bb7100>('message', '')\nE    +        where <built-in method get of dict object at 0x7fbfc3bb7100> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\nE    +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fbfc3bb7100>('message', '')\nE    +        where <built-in method get of dict object at 0x7fbfc3bb7100> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "teardown": {"duration": 1.01649566399999, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "lineno": 270, "outcome": "passed", "keywords": ["test_invalid_phone_numbers", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00047438999999371845, "outcome": "passed"}, "call": {"duration": 0.00010880400000701229, "outcome": "passed"}, "teardown": {"duration": 0.541178541000022, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_negative_pricing", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00046588300000394156, "outcome": "passed"}, "call": {"duration": 9.933600000522347e-05, "outcome": "passed"}, "teardown": {"duration": 0.5274454489999982, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "lineno": 300, "outcome": "failed", "keywords": ["test_client_not_found", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004430019999972501, "outcome": "passed"}, "call": {"duration": 0.003054289999994353, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 311, "message": "assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\n +  where '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\n +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\n +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\n +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\n +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\n +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\n +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 311, "message": "in test_client_not_found"}], "log": [{"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736385.7875533, "msecs": 787.0, "relativeCreated": 27885.874032974243, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error creating conversation state: 'Mock' object is not subscriptable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736385.7883403, "msecs": 788.0, "relativeCreated": 27886.661052703857, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736385.7887712, "msecs": 788.0, "relativeCreated": 27887.091875076294, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase2_client_management.py:311: in test_client_not_found\n    assert 'not found' in response.get('message', '').lower() or \\\nE   assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\nE    +  where '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\nE    +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\nE    +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\nE    +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\nE    +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fbfd7b3fba0>()\nE    +    where <built-in method lower of str object at 0x7fbfd7b3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fbfc3d48d00>('message', '')\nE    +        where <built-in method get of dict object at 0x7fbfc3d48d00> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140461620701776'>, 'success': True}.get"}, "teardown": {"duration": 0.7231786010000008, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "lineno": 53, "outcome": "failed", "keywords": ["test_view_schedule_commands", "TestViewScheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0014256450000118548, "outcome": "passed"}, "call": {"duration": 0.005480500999993865, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 74, "message": "AssertionError: Failed to show schedule with: Show my schedule\nassert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 74, "message": "in test_view_schedule_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736386.5216582, "msecs": 521.0, "relativeCreated": 28619.97890472412, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736386.5224748, "msecs": 522.0, "relativeCreated": 28620.795488357544, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736386.5235755, "msecs": 523.0, "relativeCreated": 28621.896266937256, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}], "longrepr": "tests/test_phase3_scheduling.py:74: in test_view_schedule_commands\n    assert 'schedule' in message or 'booking' in message or \\\nE   AssertionError: Failed to show schedule with: Show my schedule\nE   assert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "teardown": {"duration": 0.6954378659999918, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "lineno": 110, "outcome": "passed", "keywords": ["test_book_session_natural_language", "critical", "pytestmark", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023624589000007745, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736387.247836, "msecs": 247.0, "relativeCreated": 29346.15683555603, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.6663444410000068, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeom43qV3be1nadkrpW'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeom43qV3be1nadkrpW'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.3304534, "msecs": 330.0, "relativeCreated": 29428.774118423462, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeomHwdCxSoqr4fS8sx'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeomHwdCxSoqr4fS8sx'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.3772454, "msecs": 377.0, "relativeCreated": 29475.566148757935, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeomjjKk2HR9wjLHzoB'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeomjjKk2HR9wjLHzoB'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.5145142, "msecs": 514.0, "relativeCreated": 29612.834930419922, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeon6ovWdBxnhzezEnw'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeon6ovWdBxnhzezEnw'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.5759816, "msecs": 575.0, "relativeCreated": 29674.302339553833, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonKhdzYQJsbqMjRUs'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonKhdzYQJsbqMjRUs'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.634738, "msecs": 634.0, "relativeCreated": 29733.05869102478, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonZqJorYUeDyWy4A4'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonZqJorYUeDyWy4A4'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.6757462, "msecs": 675.0, "relativeCreated": 29774.066925048828, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonkzWXSqpSEzADFJK'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonkzWXSqpSEzADFJK'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.7224345, "msecs": 722.0, "relativeCreated": 29820.75524330139, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonyPiVJBUwR49wWUH'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeonyPiVJBUwR49wWUH'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.7762446, "msecs": 776.0, "relativeCreated": 29874.565362930298, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooAoHtBvEUKdRk2AG'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooAoHtBvEUKdRk2AG'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.8172464, "msecs": 817.0, "relativeCreated": 29915.56715965271, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooMiFCeTCAqbDTRZR'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooMiFCeTCAqbDTRZR'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.863156, "msecs": 863.0, "relativeCreated": 29961.476802825928, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooZNECKuiFjM9LSQB'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTTeooZNECKuiFjM9LSQB'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736387.9137208, "msecs": 913.0, "relativeCreated": 30012.041568756104, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.5062013550000017, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "lineno": 144, "outcome": "passed", "keywords": ["test_booking_time_formats", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023191314999991164, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736388.4445734, "msecs": 444.0, "relativeCreated": 30542.89412498474, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.0013941449999776978, "outcome": "passed"}, "teardown": {"duration": 1.0259599030000004, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "lineno": 169, "outcome": "passed", "keywords": ["test_booking_date_parsing", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.024040527000011025, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758736389.4966233, "msecs": 496.0, "relativeCreated": 31594.94400024414, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "call": {"duration": 0.00045378100000448285, "outcome": "passed"}, "teardown": {"duration": 0.9530170189999865, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "lineno": 223, "outcome": "passed", "keywords": ["test_cancel_booking_variations", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0042903890000047795, "outcome": "passed"}, "call": {"duration": 0.009118526000008842, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4559028, "msecs": 455.0, "relativeCreated": 32554.22353744507, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4565072, "msecs": 456.0, "relativeCreated": 32554.82792854309, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4574919, "msecs": 457.0, "relativeCreated": 32555.81259727478, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4578123, "msecs": 457.0, "relativeCreated": 32556.133031845093, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4579768, "msecs": 457.0, "relativeCreated": 32556.297540664673, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4584653, "msecs": 458.0, "relativeCreated": 32556.786060333252, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4588084, "msecs": 458.0, "relativeCreated": 32557.12914466858, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.458969, "msecs": 458.0, "relativeCreated": 32557.289838790894, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.459448, "msecs": 459.0, "relativeCreated": 32557.76882171631, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4597583, "msecs": 459.0, "relativeCreated": 32558.07900428772, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.459941, "msecs": 459.0, "relativeCreated": 32558.26163291931, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4604058, "msecs": 460.0, "relativeCreated": 32558.72654914856, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.460727, "msecs": 460.0, "relativeCreated": 32559.04769897461, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4608967, "msecs": 460.0, "relativeCreated": 32559.21745300293, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4613957, "msecs": 461.0, "relativeCreated": 32559.71646308899, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4617052, "msecs": 461.0, "relativeCreated": 32560.025930404663, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4618711, "msecs": 461.0, "relativeCreated": 32560.191869735718, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.462377, "msecs": 462.0, "relativeCreated": 32560.69779396057, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.462696, "msecs": 462.0, "relativeCreated": 32561.01679801941, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4628515, "msecs": 462.0, "relativeCreated": 32561.172246932983, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4633088, "msecs": 463.0, "relativeCreated": 32561.6295337677, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4636426, "msecs": 463.0, "relativeCreated": 32561.963319778442, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4637983, "msecs": 463.0, "relativeCreated": 32562.119007110596, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.4642577, "msecs": 464.0, "relativeCreated": 32562.578439712524, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.5140739610000082, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "lineno": 248, "outcome": "passed", "keywords": ["test_reschedule_booking", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0011684319999858417, "outcome": "passed"}, "call": {"duration": 0.013806380000005447, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9809668, "msecs": 980.0, "relativeCreated": 33079.2875289917, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9816043, "msecs": 981.0, "relativeCreated": 33079.92506027222, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.990352, "msecs": 990.0, "relativeCreated": 33088.67263793945, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9906754, "msecs": 990.0, "relativeCreated": 33088.996171951294, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9908261, "msecs": 990.0, "relativeCreated": 33089.146852493286, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9913378, "msecs": 991.0, "relativeCreated": 33089.65849876404, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9916337, "msecs": 991.0, "relativeCreated": 33089.9543762207, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9917784, "msecs": 991.0, "relativeCreated": 33090.09909629822, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9922163, "msecs": 992.0, "relativeCreated": 33090.53707122803, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.992529, "msecs": 992.0, "relativeCreated": 33090.84963798523, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9926722, "msecs": 992.0, "relativeCreated": 33090.99292755127, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9931028, "msecs": 993.0, "relativeCreated": 33091.42351150513, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9933946, "msecs": 993.0, "relativeCreated": 33091.71533584595, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.9935625, "msecs": 993.0, "relativeCreated": 33091.883182525635, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736390.993974, "msecs": 993.0, "relativeCreated": 33092.294692993164, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.8307970839999825, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "lineno": 283, "outcome": "passed", "keywords": ["test_double_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006060170000239395, "outcome": "passed"}, "call": {"duration": 0.003742150000022093, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736391.8298974, "msecs": 829.0, "relativeCreated": 33928.218126297, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.5449424640000018, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "lineno": 313, "outcome": "passed", "keywords": ["test_past_date_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005961779999950068, "outcome": "passed"}, "call": {"duration": 0.003606304999976828, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758736392.3797095, "msecs": 379.0, "relativeCreated": 34478.03020477295, "thread": 140461935401856, "threadName": "MainThread", "processName": "MainProcess", "process": 2182}]}, "teardown": {"duration": 0.5468198989999848, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "lineno": 334, "outcome": "passed", "keywords": ["test_invalid_time_slots", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000600536999996848, "outcome": "passed"}, "call": {"duration": 0.0005552010000258178, "outcome": "passed"}, "teardown": {"duration": 0.879379981999989, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "lineno": 227, "outcome": "passed", "keywords": ["test_new_trainer_onboarding", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002899239999862857, "outcome": "passed"}, "call": {"duration": 0.007036750999986907, "outcome": "passed"}, "teardown": {"duration": 0.5876940790000162, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "lineno": 242, "outcome": "passed", "keywords": ["test_trainer_recognition", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003557470000146168, "outcome": "passed"}, "call": {"duration": 0.0029945379999958277, "outcome": "passed"}, "teardown": {"duration": 1.2651059200000248, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "lineno": 269, "outcome": "passed", "keywords": ["test_add_client_variations", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00030125500001076944, "outcome": "passed"}, "call": {"duration": 0.007933643000001211, "outcome": "passed"}, "teardown": {"duration": 0.551181205000006, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "lineno": 278, "outcome": "passed", "keywords": ["test_view_clients", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00028760899999724643, "outcome": "passed"}, "call": {"duration": 0.0027784719999885965, "outcome": "passed"}, "teardown": {"duration": 0.5294983000000002, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_custom_pricing", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002825600000164741, "outcome": "passed"}, "call": {"duration": 0.004758406999997078, "outcome": "passed"}, "teardown": {"duration": 1.2947792239999956, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "lineno": 299, "outcome": "passed", "keywords": ["test_view_schedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00035379400000579153, "outcome": "passed"}, "call": {"duration": 0.004839529000008724, "outcome": "passed"}, "teardown": {"duration": 0.9791737150000017, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "lineno": 308, "outcome": "passed", "keywords": ["test_book_sessions", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00030847799999378367, "outcome": "passed"}, "call": {"duration": 0.0027511010000011993, "outcome": "passed"}, "teardown": {"duration": 0.6965381069999808, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "lineno": 317, "outcome": "failed", "keywords": ["test_cancel_reschedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029186700001559984, "outcome": "passed"}, "call": {"duration": 0.010133880000012141, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 329, "message": "assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\n +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fbfd42ac810>()\n +    where <built-in method lower of str object at 0x7fbfd42ac810> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\n +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fbfd42ac810>()\n +    where <built-in method lower of str object at 0x7fbfd42ac810> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 329, "message": "in test_cancel_reschedule"}], "longrepr": "tests/test_refiloe_complete.py:329: in test_cancel_reschedule\n    assert \"reschedul\" in response['message'].lower() or \"moved\" in response['message'].lower()\nE   assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\nE    +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fbfd42ac810>()\nE    +    where <built-in method lower of str object at 0x7fbfd42ac810> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\nE    +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fbfd42ac810>()\nE    +    where <built-in method lower of str object at 0x7fbfd42ac810> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "teardown": {"duration": 0.5410671829999956, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "lineno": 334, "outcome": "passed", "keywords": ["test_setup_habits", "TestPhase4_HabitTracking", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002844740000114143, "outcome": "passed"}, "call": {"duration": 0.00478303200000596, "outcome": "passed"}, "teardown": {"duration": 0.511213889000004, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "lineno": 347, "outcome": "passed", "keywords": ["test_send_workouts", "TestPhase5_WorkoutsAssessments", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00030308800000966585, "outcome": "passed"}, "call": {"duration": 0.004489602000006698, "outcome": "passed"}, "teardown": {"duration": 1.2172000799999978, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "lineno": 360, "outcome": "failed", "keywords": ["test_request_payment", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029999299999872164, "outcome": "passed"}, "call": {"duration": 0.005809136999999964, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 368, "message": "assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\n +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fbfd424e0b0>()\n +    where <built-in method lower of str object at 0x7fbfd424e0b0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\n +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fbfd424e0b0>()\n +    where <built-in method lower of str object at 0x7fbfd424e0b0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 368, "message": "in test_request_payment"}], "longrepr": "tests/test_refiloe_complete.py:368: in test_request_payment\n    assert \"payment\" in response['message'].lower() or \"invoice\" in response['message'].lower()\nE   assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\nE    +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fbfd424e0b0>()\nE    +    where <built-in method lower of str object at 0x7fbfd424e0b0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\nE    +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fbfd424e0b0>()\nE    +    where <built-in method lower of str object at 0x7fbfd424e0b0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "teardown": {"duration": 0.6887235320000116, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "lineno": 369, "outcome": "passed", "keywords": ["test_check_revenue", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002817579999998543, "outcome": "passed"}, "call": {"duration": 0.004763356000012209, "outcome": "passed"}, "teardown": {"duration": 0.512843719000017, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "lineno": 381, "outcome": "passed", "keywords": ["test_client_booking", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003032780000182811, "outcome": "passed"}, "call": {"duration": 0.0027424049999922318, "outcome": "passed"}, "teardown": {"duration": 0.8720114709999791, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "lineno": 390, "outcome": "passed", "keywords": ["test_client_habit_logging", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00034549800000149844, "outcome": "passed"}, "call": {"duration": 0.007564620000010791, "outcome": "passed"}, "teardown": {"duration": 0.5547865809999735, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "lineno": 403, "outcome": "passed", "keywords": ["test_natural_language_understanding", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003239680000035605, "outcome": "passed"}, "call": {"duration": 0.0026872309999816935, "outcome": "passed"}, "teardown": {"duration": 1.0026874720000194, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "lineno": 412, "outcome": "failed", "keywords": ["test_error_handling", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000297789000001103, "outcome": "passed"}, "call": {"duration": 0.004858594000012317, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 424, "message": "assert False\n +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7fbfc4fb7680>)"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 424, "message": "in test_error_handling"}], "longrepr": "tests/test_refiloe_complete.py:424: in test_error_handling\n    assert any(word in response['message'].lower() for word in [\"past\", \"future\", \"cannot\"])\nE   assert False\nE    +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7fbfc4fb7680>)"}, "teardown": {"duration": 0.5397129760000041, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "lineno": 433, "outcome": "passed", "keywords": ["test_trainer_registration_step_7_currency_parsing", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00033133200000179386, "outcome": "passed"}, "call": {"duration": 0.0006756379999899309, "outcome": "passed"}, "teardown": {"duration": 0.8358073619999971, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "lineno": 457, "outcome": "passed", "keywords": ["test_ai_responds_naturally_not_rigid_commands", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029335099998206715, "outcome": "passed"}, "call": {"duration": 0.0028158220000022993, "outcome": "passed"}, "teardown": {"duration": 0.6816011870000125, "outcome": "passed"}}], "warnings": [{"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "\nPyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),\n(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)\nbut was not found to be installed on your system.\nIf this would cause problems for you,\nplease provide us feedback at https://github.com/pandas-dev/pandas/issues/54466\n        ", "category": "DeprecationWarning", "when": "runtest", "filename": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/analytics.py", "lineno": 7}]}