{"created": 1758614271.8119392, "duration": 58.921480655670166, "exitcode": 1, "root": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant", "environment": {}, "summary": {"passed": 44, "failed": 12, "total": 56, "collected": 56}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/__init__.py", "type": "Package"}]}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "type": "Function", "lineno": 130}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "type": "Function", "lineno": 136}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "type": "Function", "lineno": 143}]}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "type": "Function", "lineno": 165}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "type": "Function", "lineno": 170}]}, {"nodeid": "tests/test_conversation_flows.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "type": "Class"}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "type": "Class"}]}, {"nodeid": "tests/test_debug.py", "outcome": "passed", "result": [{"nodeid": "tests/test_debug.py::test_python_version", "type": "Function", "lineno": 9}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "type": "Function", "lineno": 14}, {"nodeid": "tests/test_debug.py::test_project_structure", "type": "Function", "lineno": 28}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "type": "Function", "lineno": 48}, {"nodeid": "tests/test_debug.py::test_check_requirements", "type": "Function", "lineno": 84}]}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "type": "Function", "lineno": 56}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "type": "Function", "lineno": 149}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "type": "Function", "lineno": 168}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "type": "Function", "lineno": 181}]}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "type": "Function", "lineno": 238}]}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "type": "Function", "lineno": 268}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "type": "Function", "lineno": 284}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "type": "Function", "lineno": 298}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "type": "Function", "lineno": 315}]}, {"nodeid": "tests/test_phase1_registration.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "type": "Function", "lineno": 47}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "type": "Function", "lineno": 75}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "type": "Function", "lineno": 100}]}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "type": "Function", "lineno": 140}]}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "type": "Function", "lineno": 188}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "type": "Function", "lineno": 220}]}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "type": "Function", "lineno": 253}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "type": "Function", "lineno": 270}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "type": "Function", "lineno": 286}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "type": "Function", "lineno": 300}]}, {"nodeid": "tests/test_phase2_client_management.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "type": "Function", "lineno": 53}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "type": "Function", "lineno": 110}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "type": "Function", "lineno": 144}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "type": "Function", "lineno": 169}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "type": "Function", "lineno": 223}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "type": "Function", "lineno": 248}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "type": "Function", "lineno": 283}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "type": "Function", "lineno": 313}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_phase3_scheduling.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "type": "Class"}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "type": "Function", "lineno": 227}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "type": "Function", "lineno": 242}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "type": "Function", "lineno": 269}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "type": "Function", "lineno": 278}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "type": "Function", "lineno": 286}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "type": "Function", "lineno": 299}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "type": "Function", "lineno": 308}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "type": "Function", "lineno": 317}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "type": "Function", "lineno": 347}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "type": "Function", "lineno": 360}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "type": "Function", "lineno": 369}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "type": "Function", "lineno": 381}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "type": "Function", "lineno": 390}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "type": "Function", "lineno": 403}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "type": "Function", "lineno": 412}]}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "type": "Function", "lineno": 433}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "type": "Function", "lineno": 457}]}, {"nodeid": "tests/test_refiloe_complete.py", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "type": "Class"}]}, {"nodeid": "tests/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py", "type": "Module"}, {"nodeid": "tests/test_debug.py", "type": "Module"}, {"nodeid": "tests/test_phase1_registration.py", "type": "Module"}, {"nodeid": "tests/test_phase2_client_management.py", "type": "Module"}, {"nodeid": "tests/test_phase3_scheduling.py", "type": "Module"}, {"nodeid": "tests/test_refiloe_complete.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "lineno": 130, "outcome": "passed", "keywords": ["test_imports_work", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005322800000016059, "outcome": "passed"}, "call": {"duration": 0.0331681250000031, "outcome": "passed"}, "teardown": {"duration": 1.4332174179999981, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "lineno": 136, "outcome": "passed", "keywords": ["test_mock_message", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00035124899999772197, "outcome": "passed"}, "call": {"duration": 0.022053440000000535, "outcome": "passed"}, "teardown": {"duration": 1.4173752769999979, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "lineno": 143, "outcome": "passed", "keywords": ["test_trainer_registration_mock", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00032244599999842194, "outcome": "passed"}, "call": {"duration": 0.02370617599999747, "outcome": "passed"}, "teardown": {"duration": 1.2410094479999998, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "lineno": 165, "outcome": "passed", "keywords": ["test_basic_setup", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023004357000004916, "outcome": "passed"}, "call": {"duration": 0.0001089049999976055, "outcome": "passed"}, "teardown": {"duration": 1.4390174759999965, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "lineno": 170, "outcome": "passed", "keywords": ["test_mock_registration_flow", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022391155000001106, "outcome": "passed"}, "call": {"duration": 0.0001966949999996359, "outcome": "passed"}, "teardown": {"duration": 1.2096240680000037, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_python_version", "lineno": 9, "outcome": "passed", "keywords": ["test_python_version", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002738129999997341, "outcome": "passed"}, "call": {"duration": 0.00010348499999679461, "outcome": "passed"}, "teardown": {"duration": 1.3904296190000025, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "lineno": 14, "outcome": "passed", "keywords": ["test_can_import_basic_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00027014700000194125, "outcome": "passed"}, "call": {"duration": 9.213300000254776e-05, "outcome": "passed"}, "teardown": {"duration": 1.3990036369999999, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_project_structure", "lineno": 28, "outcome": "passed", "keywords": ["test_project_structure", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002821400000030394, "outcome": "passed"}, "call": {"duration": 0.00024507999999912045, "outcome": "passed"}, "teardown": {"duration": 1.2031151300000005, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "lineno": 48, "outcome": "passed", "keywords": ["test_can_import_refiloe_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00033867499999473694, "outcome": "passed"}, "call": {"duration": 0.0004524290000063047, "outcome": "passed"}, "teardown": {"duration": 1.2073115729999984, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_check_requirements", "lineno": 84, "outcome": "passed", "keywords": ["test_check_requirements", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00026375500000597185, "outcome": "passed"}, "call": {"duration": 0.07439552299999264, "outcome": "passed"}, "teardown": {"duration": 0.9965198800000081, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "lineno": 56, "outcome": "failed", "keywords": ["test_complete_trainer_registration_flow", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.004045571000006021, "outcome": "passed"}, "call": {"duration": 0.0018812659999980497, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 80, "message": "assert 'step 1' in \"welcome back, there! you're already registered. how can i help you today?\"\n +  where \"welcome back, there! you're already registered. how can i help you today?\" = <built-in method lower of str object at 0x7f843e3840b0>()\n +    where <built-in method lower of str object at 0x7f843e3840b0> = \"Welcome back, there! You're already registered. How can I help you today?\".lower"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 80, "message": "in test_complete_trainer_registration_flow"}], "longrepr": "tests/test_phase1_registration.py:80: in test_complete_trainer_registration_flow\n    assert \"step 1\" in response.lower()\nE   assert 'step 1' in \"welcome back, there! you're already registered. how can i help you today?\"\nE    +  where \"welcome back, there! you're already registered. how can i help you today?\" = <built-in method lower of str object at 0x7f843e3840b0>()\nE    +    where <built-in method lower of str object at 0x7f843e3840b0> = \"Welcome back, there! You're already registered. How can I help you today?\".lower"}, "teardown": {"duration": 0.7980092289999874, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "lineno": 149, "outcome": "passed", "keywords": ["test_currency_parsing_variations", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.004411098000005609, "outcome": "passed"}, "call": {"duration": 0.0004866820000017924, "outcome": "passed"}, "teardown": {"duration": 1.413046405000003, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "lineno": 168, "outcome": "passed", "keywords": ["test_registration_with_missing_fields", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.002050382999996714, "outcome": "passed"}, "call": {"duration": 0.0003244179999910557, "outcome": "passed"}, "teardown": {"duration": 1.391252332999997, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "lineno": 181, "outcome": "failed", "keywords": ["test_trainer_recognition_after_registration", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0018887900000095215, "outcome": "passed"}, "call": {"duration": 0.7942622419999879, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 209, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7f842f4aa880>('success')\n +    where <built-in method get of dict object at 0x7f842f4aa880> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 209, "message": "in test_trainer_recognition_after_registration"}], "log": [{"name": "refiloe", "msg": "Background scheduler started", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614230.9452703, "msecs": 945.0, "relativeCreated": 18751.110315322876, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Routes setup complete", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614230.9461935, "msecs": 946.0, "relativeCreated": 18752.033472061157, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614230.9511013, "msecs": 951.0, "relativeCreated": 18756.941318511963, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614230.952738, "msecs": 952.0, "relativeCreated": 18758.578062057495, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase1_registration.py:209: in test_trainer_recognition_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7f842f4aa880>('success')\nE    +    where <built-in method get of dict object at 0x7f842f4aa880> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 1.4361800190000054, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "lineno": 238, "outcome": "failed", "keywords": ["test_client_receives_welcome_after_registration", "TestClientRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.004523525000010409, "outcome": "passed"}, "call": {"duration": 0.003268381000012255, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 254, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7f842f54a180>('success')\n +    where <built-in method get of dict object at 0x7f842f54a180> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 254, "message": "in test_client_receives_welcome_after_registration"}], "log": [{"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614232.3996773, "msecs": 399.0, "relativeCreated": 20205.517292022705, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614232.4020164, "msecs": 402.0, "relativeCreated": 20207.85641670227, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase1_registration.py:254: in test_client_receives_welcome_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7f842f54a180>('success')\nE    +    where <built-in method get of dict object at 0x7f842f54a180> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 0.7653283620000053, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "lineno": 268, "outcome": "passed", "keywords": ["test_duplicate_registration_attempt", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006298309999976937, "outcome": "passed"}, "call": {"duration": 0.003527105999992841, "outcome": "passed"}, "teardown": {"duration": 1.204478770999998, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "lineno": 284, "outcome": "passed", "keywords": ["test_invalid_email_format", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006044929999973192, "outcome": "passed"}, "call": {"duration": 0.0002842220000047746, "outcome": "passed"}, "teardown": {"duration": 1.2007005329999885, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "lineno": 298, "outcome": "passed", "keywords": ["test_extremely_long_input", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005682860000035816, "outcome": "passed"}, "call": {"duration": 0.00011049699999432505, "outcome": "passed"}, "teardown": {"duration": 1.3747023840000026, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "lineno": 315, "outcome": "passed", "keywords": ["test_special_characters_in_name", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006088620000070932, "outcome": "passed"}, "call": {"duration": 0.00011567699999659453, "outcome": "passed"}, "teardown": {"duration": 1.4163769040000034, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "lineno": 47, "outcome": "passed", "keywords": ["test_add_client_command_variations", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023056713999991985, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614238.4000893, "msecs": 400.0, "relativeCreated": 26205.929279327393, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.018679285999994022, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4010081, "msecs": 401.0, "relativeCreated": 26206.84814453125, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4017856, "msecs": 401.0, "relativeCreated": 26207.6256275177, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.409711, "msecs": 409.0, "relativeCreated": 26215.550899505615, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4100406, "msecs": 410.0, "relativeCreated": 26215.880632400513, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.410208, "msecs": 410.0, "relativeCreated": 26216.048002243042, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4107733, "msecs": 410.0, "relativeCreated": 26216.61329269409, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.411091, "msecs": 411.0, "relativeCreated": 26216.931104660034, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4112487, "msecs": 411.0, "relativeCreated": 26217.08869934082, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4117594, "msecs": 411.0, "relativeCreated": 26217.599391937256, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4121044, "msecs": 412.0, "relativeCreated": 26217.944383621216, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4122992, "msecs": 412.0, "relativeCreated": 26218.13917160034, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4128091, "msecs": 412.0, "relativeCreated": 26218.64914894104, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4131267, "msecs": 413.0, "relativeCreated": 26218.966722488403, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4133291, "msecs": 413.0, "relativeCreated": 26219.16913986206, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4138033, "msecs": 413.0, "relativeCreated": 26219.643354415894, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4141302, "msecs": 414.0, "relativeCreated": 26219.97022628784, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4143114, "msecs": 414.0, "relativeCreated": 26220.15142440796, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4148211, "msecs": 414.0, "relativeCreated": 26220.661163330078, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4151309, "msecs": 415.0, "relativeCreated": 26220.97086906433, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.415309, "msecs": 415.0, "relativeCreated": 26221.14896774292, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4158068, "msecs": 415.0, "relativeCreated": 26221.646785736084, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4162383, "msecs": 416.0, "relativeCreated": 26222.078323364258, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4164152, "msecs": 416.0, "relativeCreated": 26222.25522994995, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4169474, "msecs": 416.0, "relativeCreated": 26222.787380218506, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4172816, "msecs": 417.0, "relativeCreated": 26223.121643066406, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4174433, "msecs": 417.0, "relativeCreated": 26223.283290863037, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4179, "msecs": 417.0, "relativeCreated": 26223.740100860596, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4182262, "msecs": 418.0, "relativeCreated": 26224.066257476807, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4184022, "msecs": 418.0, "relativeCreated": 26224.242210388184, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614238.4188697, "msecs": 418.0, "relativeCreated": 26224.7097492218, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 1.0080506540000016, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "lineno": 75, "outcome": "passed", "keywords": ["test_phone_number_normalization", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022898337999990304, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614239.4505262, "msecs": 450.0, "relativeCreated": 27256.36625289917, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.00020277000000135104, "outcome": "passed"}, "teardown": {"duration": 1.223793158999996, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "lineno": 100, "outcome": "passed", "keywords": ["test_add_client_with_special_names", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02746465199999193, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614240.7026517, "msecs": 702.0, "relativeCreated": 28508.49175453186, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.04733780600000159, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7035806, "msecs": 703.0, "relativeCreated": 28509.42063331604, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7041962, "msecs": 704.0, "relativeCreated": 28510.03623008728, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7048705, "msecs": 704.0, "relativeCreated": 28510.71047782898, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7051945, "msecs": 705.0, "relativeCreated": 28511.03448867798, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7053795, "msecs": 705.0, "relativeCreated": 28511.21950149536, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7058804, "msecs": 705.0, "relativeCreated": 28511.720418930054, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.706191, "msecs": 706.0, "relativeCreated": 28512.031078338623, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7063677, "msecs": 706.0, "relativeCreated": 28512.207746505737, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7068195, "msecs": 706.0, "relativeCreated": 28512.659549713135, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.709187, "msecs": 709.0, "relativeCreated": 28515.027046203613, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7093897, "msecs": 709.0, "relativeCreated": 28515.22970199585, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7103348, "msecs": 710.0, "relativeCreated": 28516.17479324341, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.710654, "msecs": 710.0, "relativeCreated": 28516.494035720825, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7473805, "msecs": 747.0, "relativeCreated": 28553.220510482788, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.748213, "msecs": 748.0, "relativeCreated": 28554.05306816101, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7485397, "msecs": 748.0, "relativeCreated": 28554.37970161438, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7486968, "msecs": 748.0, "relativeCreated": 28554.536819458008, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.749154, "msecs": 749.0, "relativeCreated": 28554.994106292725, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7494624, "msecs": 749.0, "relativeCreated": 28555.302381515503, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.7496116, "msecs": 749.0, "relativeCreated": 28555.45163154602, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614240.750063, "msecs": 750.0, "relativeCreated": 28555.90295791626, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 1.442546336999996, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "lineno": 140, "outcome": "failed", "keywords": ["test_view_clients_commands", "TestViewClientsReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000993833999999083, "outcome": "passed"}, "call": {"duration": 0.0028476009999991447, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 160, "message": "AssertionError: Failed to list clients with command: Show my clients\nassert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 160, "message": "in test_view_clients_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.1953523, "msecs": 195.0, "relativeCreated": 30001.192331314087, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.1959689, "msecs": 195.0, "relativeCreated": 30001.808881759644, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.197052, "msecs": 197.0, "relativeCreated": 30002.892017364502, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase2_client_management.py:160: in test_view_clients_commands\n    assert 'sarah' in message or 'john' in message or 'mike' in message or \\\nE   AssertionError: Failed to list clients with command: Show my clients\nE   assert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "teardown": {"duration": 0.545682381000006, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "lineno": 188, "outcome": "passed", "keywords": ["test_set_custom_pricing_variations", "critical", "pytestmark", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0013871419999986756, "outcome": "passed"}, "call": {"duration": 0.013416274000007888, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7517354, "msecs": 751.0, "relativeCreated": 30557.575464248657, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.752394, "msecs": 752.0, "relativeCreated": 30558.233976364136, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7533205, "msecs": 753.0, "relativeCreated": 30559.160470962524, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.75369, "msecs": 753.0, "relativeCreated": 30559.530019760132, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7538831, "msecs": 753.0, "relativeCreated": 30559.723138809204, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7543535, "msecs": 754.0, "relativeCreated": 30560.19353866577, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.754668, "msecs": 754.0, "relativeCreated": 30560.508012771606, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7548454, "msecs": 754.0, "relativeCreated": 30560.685396194458, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7553098, "msecs": 755.0, "relativeCreated": 30561.149835586548, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7556183, "msecs": 755.0, "relativeCreated": 30561.458349227905, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7557974, "msecs": 755.0, "relativeCreated": 30561.63740158081, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.756242, "msecs": 756.0, "relativeCreated": 30562.082052230835, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7565725, "msecs": 756.0, "relativeCreated": 30562.41250038147, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7567303, "msecs": 756.0, "relativeCreated": 30562.570333480835, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7596457, "msecs": 759.0, "relativeCreated": 30565.48571586609, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7599607, "msecs": 759.0, "relativeCreated": 30565.800666809082, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.760108, "msecs": 760.0, "relativeCreated": 30565.948009490967, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7605684, "msecs": 760.0, "relativeCreated": 30566.408395767212, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.760908, "msecs": 760.0, "relativeCreated": 30566.747903823853, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.761063, "msecs": 761.0, "relativeCreated": 30566.903114318848, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7615237, "msecs": 761.0, "relativeCreated": 30567.363739013672, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.76183, "msecs": 761.0, "relativeCreated": 30567.670106887817, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.762005, "msecs": 762.0, "relativeCreated": 30567.845106124878, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614242.7624621, "msecs": 762.0, "relativeCreated": 30568.302154541016, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 0.548459765000004, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "lineno": 220, "outcome": "failed", "keywords": ["test_check_client_pricing", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.001447954999989065, "outcome": "passed"}, "call": {"duration": 0.0025751199999888286, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 239, "message": "AssertionError: Failed to show pricing with: What is Sarah's rate?\nassert ('r' in '' or 'rand' in '' or False)\n +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7f842f4b7a00>)"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 239, "message": "in test_check_client_pricing"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614243.3138435, "msecs": 313.0, "relativeCreated": 31119.683504104614, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614243.3144755, "msecs": 314.0, "relativeCreated": 31120.315551757812, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614243.3154917, "msecs": 315.0, "relativeCreated": 31121.331691741943, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase2_client_management.py:239: in test_check_client_pricing\n    assert 'r' in message or 'rand' in message or \\\nE   AssertionError: Failed to show pricing with: What is Sarah's rate?\nE   assert ('r' in '' or 'rand' in '' or False)\nE    +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7f842f4b7a00>)"}, "teardown": {"duration": 0.7778306669999893, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "lineno": 253, "outcome": "failed", "keywords": ["test_add_client_with_duplicate_phone", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004713040000012825, "outcome": "passed"}, "call": {"duration": 0.005236772000003498, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 268, "message": "AssertionError: assert ('already' in '' or 'exists' in '')\n +  where '' = <built-in method lower of str object at 0x7f844213fba0>()\n +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f842f547240>('message', '')\n +        where <built-in method get of dict object at 0x7f842f547240> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\n +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f842f547240>('message', '')\n +        where <built-in method get of dict object at 0x7f842f547240> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 268, "message": "in test_add_client_with_duplicate_phone"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614244.0999682, "msecs": 99.0, "relativeCreated": 31905.808210372925, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614244.1026893, "msecs": 102.0, "relativeCreated": 31908.52928161621, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614244.1035945, "msecs": 103.0, "relativeCreated": 31909.43455696106, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase2_client_management.py:268: in test_add_client_with_duplicate_phone\n    assert 'already' in response.get('message', '').lower() or \\\nE   AssertionError: assert ('already' in '' or 'exists' in '')\nE    +  where '' = <built-in method lower of str object at 0x7f844213fba0>()\nE    +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f842f547240>('message', '')\nE    +        where <built-in method get of dict object at 0x7f842f547240> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\nE    +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f842f547240>('message', '')\nE    +        where <built-in method get of dict object at 0x7f842f547240> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get"}, "teardown": {"duration": 0.9711784689999945, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "lineno": 270, "outcome": "passed", "keywords": ["test_invalid_phone_numbers", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000599734999994439, "outcome": "passed"}, "call": {"duration": 0.00015673400000082438, "outcome": "passed"}, "teardown": {"duration": 1.0194743920000064, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_negative_pricing", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00044210900000507536, "outcome": "passed"}, "call": {"duration": 0.00012001500000735632, "outcome": "passed"}, "teardown": {"duration": 0.773801039999995, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "lineno": 300, "outcome": "failed", "keywords": ["test_client_not_found", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004336929999908534, "outcome": "passed"}, "call": {"duration": 0.005219199000009667, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 311, "message": "assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\n +  where '' = <built-in method lower of str object at 0x7f844213fba0>()\n +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\n +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\n +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\n +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\n +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\n +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 311, "message": "in test_client_not_found"}], "log": [{"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614246.8828914, "msecs": 882.0, "relativeCreated": 34688.73143196106, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error creating conversation state: 'Mock' object is not subscriptable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614246.8835363, "msecs": 883.0, "relativeCreated": 34689.37635421753, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614246.8840091, "msecs": 884.0, "relativeCreated": 34689.84913825989, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase2_client_management.py:311: in test_client_not_found\n    assert 'not found' in response.get('message', '').lower() or \\\nE   assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\nE    +  where '' = <built-in method lower of str object at 0x7f844213fba0>()\nE    +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\nE    +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\nE    +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\nE    +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f844213fba0>()\nE    +    where <built-in method lower of str object at 0x7f844213fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f843e1f0a40>('message', '')\nE    +        where <built-in method get of dict object at 0x7f843e1f0a40> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140205687985936'>, 'success': True}.get"}, "teardown": {"duration": 0.7785706610000034, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "lineno": 53, "outcome": "failed", "keywords": ["test_view_schedule_commands", "TestViewScheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00134070500000405, "outcome": "passed"}, "call": {"duration": 0.00521732599999325, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 74, "message": "AssertionError: Failed to show schedule with: Show my schedule\nassert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 74, "message": "in test_view_schedule_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614247.6720479, "msecs": 672.0, "relativeCreated": 35477.887868881226, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614247.6729953, "msecs": 672.0, "relativeCreated": 35478.835344314575, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614247.673972, "msecs": 673.0, "relativeCreated": 35479.811906814575, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}], "longrepr": "tests/test_phase3_scheduling.py:74: in test_view_schedule_commands\n    assert 'schedule' in message or 'booking' in message or \\\nE   AssertionError: Failed to show schedule with: Show my schedule\nE   assert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "teardown": {"duration": 0.7843912189999998, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "lineno": 110, "outcome": "passed", "keywords": ["test_book_session_natural_language", "critical", "pytestmark", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023229010999997968, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614248.4865036, "msecs": 486.0, "relativeCreated": 36292.343616485596, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.7904299960000003, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPKgpSv7XUraMYBE4'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPKgpSv7XUraMYBE4'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614248.5575688, "msecs": 557.0, "relativeCreated": 36363.40880393982, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPX6N4LqxPwD26YzQ'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPX6N4LqxPwD26YzQ'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614248.609952, "msecs": 609.0, "relativeCreated": 36415.7919883728, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPkjQpfn8sELGYpRw'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaPkjQpfn8sELGYpRw'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614248.868812, "msecs": 868.0, "relativeCreated": 36674.652099609375, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaQqiJgEpM6wEy9NPH'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaQqiJgEpM6wEy9NPH'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614248.9118986, "msecs": 911.0, "relativeCreated": 36717.73862838745, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaR2dFtC63Fdn3baZM'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaR2dFtC63Fdn3baZM'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614248.957484, "msecs": 957.0, "relativeCreated": 36763.32402229309, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRGm48ZzH6aQwtrgd'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRGm48ZzH6aQwtrgd'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.0337386, "msecs": 33.0, "relativeCreated": 36839.57862854004, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRZ8S5CccgvAwxqdS'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRZ8S5CccgvAwxqdS'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.0779321, "msecs": 77.0, "relativeCreated": 36883.772134780884, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRjnkjQ5dzqEhmpV8'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRjnkjQ5dzqEhmpV8'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.1209714, "msecs": 120.0, "relativeCreated": 36926.8114566803, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRuxSLyqa8rhmCngT'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaRuxSLyqa8rhmCngT'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.1598241, "msecs": 159.0, "relativeCreated": 36965.66414833069, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaS6sWLLnBDrExpQVw'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaS6sWLLnBDrExpQVw'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.2214613, "msecs": 221.0, "relativeCreated": 37027.30131149292, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaSMzfggPFHfckXfyc'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQyaSMzfggPFHfckXfyc'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614249.2765522, "msecs": 276.0, "relativeCreated": 37082.39221572876, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 1.2231571690000038, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "lineno": 144, "outcome": "failed", "keywords": ["test_booking_time_formats", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023043506000007596, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614250.5240507, "msecs": 524.0, "relativeCreated": 38329.890727996826, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.0010110859999912236, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 168, "message": "AssertionError: Failed to validate time: 9am\nassert False == True"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 168, "message": "in test_booking_time_formats"}], "longrepr": "tests/test_phase3_scheduling.py:168: in test_booking_time_formats\n    assert is_valid == True, f\"Failed to validate time: {time_format}\"\nE   AssertionError: Failed to validate time: 9am\nE   assert False == True"}, "teardown": {"duration": 0.5679175249999986, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "lineno": 169, "outcome": "passed", "keywords": ["test_booking_date_parsing", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023040100000002894, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758614251.122629, "msecs": 122.0, "relativeCreated": 38928.46894264221, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "call": {"duration": 0.00044755999999779306, "outcome": "passed"}, "teardown": {"duration": 0.9756935209999966, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "lineno": 223, "outcome": "passed", "keywords": ["test_cancel_booking_variations", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.001148505000003297, "outcome": "passed"}, "call": {"duration": 0.013542017000006012, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1014965, "msecs": 101.0, "relativeCreated": 39907.336473464966, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1020963, "msecs": 102.0, "relativeCreated": 39907.936334609985, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1031694, "msecs": 103.0, "relativeCreated": 39909.00945663452, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1035185, "msecs": 103.0, "relativeCreated": 39909.358501434326, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1036787, "msecs": 103.0, "relativeCreated": 39909.51871871948, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1041884, "msecs": 104.0, "relativeCreated": 39910.0284576416, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1045196, "msecs": 104.0, "relativeCreated": 39910.35962104797, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1046705, "msecs": 104.0, "relativeCreated": 39910.510540008545, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1051362, "msecs": 105.0, "relativeCreated": 39910.97617149353, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1054492, "msecs": 105.0, "relativeCreated": 39911.28921508789, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.105597, "msecs": 105.0, "relativeCreated": 39911.43703460693, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.106029, "msecs": 106.0, "relativeCreated": 39911.869049072266, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.106364, "msecs": 106.0, "relativeCreated": 39912.2040271759, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.106518, "msecs": 106.0, "relativeCreated": 39912.358045578, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1069517, "msecs": 106.0, "relativeCreated": 39912.79172897339, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1072438, "msecs": 107.0, "relativeCreated": 39913.08379173279, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1074414, "msecs": 107.0, "relativeCreated": 39913.28144073486, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1078835, "msecs": 107.0, "relativeCreated": 39913.72346878052, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.108193, "msecs": 108.0, "relativeCreated": 39914.03293609619, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1083653, "msecs": 108.0, "relativeCreated": 39914.20531272888, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1132386, "msecs": 113.0, "relativeCreated": 39919.07858848572, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1135898, "msecs": 113.0, "relativeCreated": 39919.429779052734, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1137486, "msecs": 113.0, "relativeCreated": 39919.588565826416, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.1142318, "msecs": 114.0, "relativeCreated": 39920.071840286255, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 0.7719433529999975, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "lineno": 248, "outcome": "passed", "keywords": ["test_reschedule_booking", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0011359100000021272, "outcome": "passed"}, "call": {"duration": 0.00827472899999293, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8887954, "msecs": 888.0, "relativeCreated": 40694.63539123535, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8914227, "msecs": 891.0, "relativeCreated": 40697.26276397705, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8923314, "msecs": 892.0, "relativeCreated": 40698.17137718201, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8926702, "msecs": 892.0, "relativeCreated": 40698.51016998291, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8928337, "msecs": 892.0, "relativeCreated": 40698.673725128174, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8933668, "msecs": 893.0, "relativeCreated": 40699.206829071045, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8936937, "msecs": 893.0, "relativeCreated": 40699.53370094299, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8938546, "msecs": 893.0, "relativeCreated": 40699.69463348389, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.894384, "msecs": 894.0, "relativeCreated": 40700.22392272949, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8946924, "msecs": 894.0, "relativeCreated": 40700.53243637085, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8948503, "msecs": 894.0, "relativeCreated": 40700.690269470215, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8953493, "msecs": 895.0, "relativeCreated": 40701.189279556274, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8956604, "msecs": 895.0, "relativeCreated": 40701.500415802, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8958154, "msecs": 895.0, "relativeCreated": 40701.65538787842, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614252.8962848, "msecs": 896.0, "relativeCreated": 40702.12483406067, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 1.016194146999993, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "lineno": 283, "outcome": "passed", "keywords": ["test_double_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000530284999996411, "outcome": "passed"}, "call": {"duration": 0.0014367149999969797, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614253.9151447, "msecs": 915.0, "relativeCreated": 41720.98469734192, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 0.9852104130000043, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "lineno": 313, "outcome": "passed", "keywords": ["test_past_date_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005232010000071341, "outcome": "passed"}, "call": {"duration": 0.001350311999999576, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758614254.9028726, "msecs": 902.0, "relativeCreated": 42708.712577819824, "thread": 140206022302592, "threadName": "MainThread", "processName": "MainProcess", "process": 2191}]}, "teardown": {"duration": 0.9707841620000011, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "lineno": 334, "outcome": "passed", "keywords": ["test_invalid_time_slots", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005099669999992784, "outcome": "passed"}, "call": {"duration": 0.00025359600000740556, "outcome": "passed"}, "teardown": {"duration": 0.7755125389999904, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "lineno": 227, "outcome": "passed", "keywords": ["test_new_trainer_onboarding", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003161230000046089, "outcome": "passed"}, "call": {"duration": 0.004663786999998365, "outcome": "passed"}, "teardown": {"duration": 0.7656545130000012, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "lineno": 242, "outcome": "passed", "keywords": ["test_trainer_recognition", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031866800000557305, "outcome": "passed"}, "call": {"duration": 0.011867968000004225, "outcome": "passed"}, "teardown": {"duration": 0.9681804669999963, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "lineno": 269, "outcome": "passed", "keywords": ["test_add_client_variations", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00027988499999764826, "outcome": "passed"}, "call": {"duration": 0.0049703290000024936, "outcome": "passed"}, "teardown": {"duration": 0.5449315700000028, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "lineno": 278, "outcome": "passed", "keywords": ["test_view_clients", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003028080000007094, "outcome": "passed"}, "call": {"duration": 0.004509775000002492, "outcome": "passed"}, "teardown": {"duration": 0.5574898869999885, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_custom_pricing", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002800950000079183, "outcome": "passed"}, "call": {"duration": 0.0028280020000011064, "outcome": "passed"}, "teardown": {"duration": 0.9736303399999997, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "lineno": 299, "outcome": "passed", "keywords": ["test_view_schedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003349979999995867, "outcome": "passed"}, "call": {"duration": 0.0047958719999883215, "outcome": "passed"}, "teardown": {"duration": 0.9591185950000067, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "lineno": 308, "outcome": "passed", "keywords": ["test_book_sessions", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003006339999984675, "outcome": "passed"}, "call": {"duration": 0.007813468999998463, "outcome": "passed"}, "teardown": {"duration": 0.7604522089999932, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "lineno": 317, "outcome": "failed", "keywords": ["test_cancel_reschedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000327605000009612, "outcome": "passed"}, "call": {"duration": 0.004960820999997395, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 329, "message": "assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\n +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f843e7bc1f0>()\n +    where <built-in method lower of str object at 0x7f843e7bc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\n +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f843e7bc1f0>()\n +    where <built-in method lower of str object at 0x7f843e7bc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 329, "message": "in test_cancel_reschedule"}], "longrepr": "tests/test_refiloe_complete.py:329: in test_cancel_reschedule\n    assert \"reschedul\" in response['message'].lower() or \"moved\" in response['message'].lower()\nE   assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\nE    +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f843e7bc1f0>()\nE    +    where <built-in method lower of str object at 0x7f843e7bc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\nE    +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f843e7bc1f0>()\nE    +    where <built-in method lower of str object at 0x7f843e7bc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "teardown": {"duration": 1.4187085820000078, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "lineno": 334, "outcome": "passed", "keywords": ["test_setup_habits", "TestPhase4_HabitTracking", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031871800000260464, "outcome": "passed"}, "call": {"duration": 0.005054185000005873, "outcome": "passed"}, "teardown": {"duration": 0.9764759570000052, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "lineno": 347, "outcome": "passed", "keywords": ["test_send_workouts", "TestPhase5_WorkoutsAssessments", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002804159999953981, "outcome": "passed"}, "call": {"duration": 0.005619506000002161, "outcome": "passed"}, "teardown": {"duration": 1.0139433249999996, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "lineno": 360, "outcome": "failed", "keywords": ["test_request_payment", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00026301399999795194, "outcome": "passed"}, "call": {"duration": 0.0028562949999866305, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 368, "message": "assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\n +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f843e7459d0>()\n +    where <built-in method lower of str object at 0x7f843e7459d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\n +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f843e7459d0>()\n +    where <built-in method lower of str object at 0x7f843e7459d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 368, "message": "in test_request_payment"}], "longrepr": "tests/test_refiloe_complete.py:368: in test_request_payment\n    assert \"payment\" in response['message'].lower() or \"invoice\" in response['message'].lower()\nE   assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\nE    +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f843e7459d0>()\nE    +    where <built-in method lower of str object at 0x7f843e7459d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\nE    +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f843e7459d0>()\nE    +    where <built-in method lower of str object at 0x7f843e7459d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "teardown": {"duration": 0.6166047520000006, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "lineno": 369, "outcome": "passed", "keywords": ["test_check_revenue", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00027681899999265625, "outcome": "passed"}, "call": {"duration": 0.004746934000010583, "outcome": "passed"}, "teardown": {"duration": 0.9593334959999993, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "lineno": 381, "outcome": "passed", "keywords": ["test_client_booking", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00028992400000049656, "outcome": "passed"}, "call": {"duration": 0.007662972999995077, "outcome": "passed"}, "teardown": {"duration": 0.5696537969999866, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "lineno": 390, "outcome": "passed", "keywords": ["test_client_habit_logging", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00025779300000294825, "outcome": "passed"}, "call": {"duration": 0.0026968690000046536, "outcome": "passed"}, "teardown": {"duration": 1.2132860460000074, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "lineno": 403, "outcome": "passed", "keywords": ["test_natural_language_understanding", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002801250000032951, "outcome": "passed"}, "call": {"duration": 0.004839246000003072, "outcome": "passed"}, "teardown": {"duration": 0.571864074000004, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "lineno": 412, "outcome": "failed", "keywords": ["test_error_handling", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00028980400000477857, "outcome": "passed"}, "call": {"duration": 0.002759195000010095, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 424, "message": "assert False\n +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7f842f5667a0>)"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 424, "message": "in test_error_handling"}], "longrepr": "tests/test_refiloe_complete.py:424: in test_error_handling\n    assert any(word in response['message'].lower() for word in [\"past\", \"future\", \"cannot\"])\nE   assert False\nE    +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7f842f5667a0>)"}, "teardown": {"duration": 0.567338792000001, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "lineno": 433, "outcome": "passed", "keywords": ["test_trainer_registration_step_7_currency_parsing", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002723409999987325, "outcome": "passed"}, "call": {"duration": 0.0007047320000026502, "outcome": "passed"}, "teardown": {"duration": 1.0242866720000023, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "lineno": 457, "outcome": "passed", "keywords": ["test_ai_responds_naturally_not_rigid_commands", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002782020000040575, "outcome": "passed"}, "call": {"duration": 0.002933572000003437, "outcome": "passed"}, "teardown": {"duration": 0.5745567929999993, "outcome": "passed"}}], "warnings": [{"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "\nPyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),\n(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)\nbut was not found to be installed on your system.\nIf this would cause problems for you,\nplease provide us feedback at https://github.com/pandas-dev/pandas/issues/54466\n        ", "category": "DeprecationWarning", "when": "runtest", "filename": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/analytics.py", "lineno": 7}]}