{"created": 1758822577.1396725, "duration": 43.7082839012146, "exitcode": 1, "root": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant", "environment": {}, "summary": {"passed": 46, "failed": 10, "total": 56, "collected": 56}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/__init__.py", "type": "Package"}]}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "type": "Function", "lineno": 130}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "type": "Function", "lineno": 136}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "type": "Function", "lineno": 143}]}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "type": "Function", "lineno": 165}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "type": "Function", "lineno": 170}]}, {"nodeid": "tests/test_conversation_flows.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "type": "Class"}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "type": "Class"}]}, {"nodeid": "tests/test_debug.py", "outcome": "passed", "result": [{"nodeid": "tests/test_debug.py::test_python_version", "type": "Function", "lineno": 9}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "type": "Function", "lineno": 14}, {"nodeid": "tests/test_debug.py::test_project_structure", "type": "Function", "lineno": 28}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "type": "Function", "lineno": 48}, {"nodeid": "tests/test_debug.py::test_check_requirements", "type": "Function", "lineno": 84}]}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "type": "Function", "lineno": 77}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "type": "Function", "lineno": 192}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "type": "Function", "lineno": 211}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "type": "Function", "lineno": 224}]}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "type": "Function", "lineno": 281}]}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "type": "Function", "lineno": 311}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "type": "Function", "lineno": 327}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "type": "Function", "lineno": 341}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "type": "Function", "lineno": 358}]}, {"nodeid": "tests/test_phase1_registration.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "type": "Function", "lineno": 47}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "type": "Function", "lineno": 75}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "type": "Function", "lineno": 100}]}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "type": "Function", "lineno": 140}]}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "type": "Function", "lineno": 188}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "type": "Function", "lineno": 220}]}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "type": "Function", "lineno": 253}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "type": "Function", "lineno": 270}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "type": "Function", "lineno": 286}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "type": "Function", "lineno": 300}]}, {"nodeid": "tests/test_phase2_client_management.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "type": "Function", "lineno": 53}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "type": "Function", "lineno": 110}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "type": "Function", "lineno": 144}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "type": "Function", "lineno": 169}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "type": "Function", "lineno": 223}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "type": "Function", "lineno": 248}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "type": "Function", "lineno": 283}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "type": "Function", "lineno": 313}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_phase3_scheduling.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "type": "Class"}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "type": "Function", "lineno": 227}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "type": "Function", "lineno": 242}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "type": "Function", "lineno": 269}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "type": "Function", "lineno": 278}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "type": "Function", "lineno": 286}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "type": "Function", "lineno": 299}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "type": "Function", "lineno": 308}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "type": "Function", "lineno": 317}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "type": "Function", "lineno": 347}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "type": "Function", "lineno": 360}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "type": "Function", "lineno": 369}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "type": "Function", "lineno": 381}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "type": "Function", "lineno": 390}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "type": "Function", "lineno": 403}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "type": "Function", "lineno": 412}]}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "type": "Function", "lineno": 433}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "type": "Function", "lineno": 457}]}, {"nodeid": "tests/test_refiloe_complete.py", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "type": "Class"}]}, {"nodeid": "tests/test_setup_fix.py", "outcome": "passed", "result": []}, {"nodeid": "tests/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py", "type": "Module"}, {"nodeid": "tests/test_debug.py", "type": "Module"}, {"nodeid": "tests/test_phase1_registration.py", "type": "Module"}, {"nodeid": "tests/test_phase2_client_management.py", "type": "Module"}, {"nodeid": "tests/test_phase3_scheduling.py", "type": "Module"}, {"nodeid": "tests/test_refiloe_complete.py", "type": "Module"}, {"nodeid": "tests/test_setup_fix.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "lineno": 130, "outcome": "passed", "keywords": ["test_imports_work", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004755240000235972, "outcome": "passed"}, "call": {"duration": 0.0329545939999889, "outcome": "passed"}, "teardown": {"duration": 0.7136911790000227, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "lineno": 136, "outcome": "passed", "keywords": ["test_mock_message", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00030590899996241205, "outcome": "passed"}, "call": {"duration": 0.022088730999996642, "outcome": "passed"}, "teardown": {"duration": 0.7183264380000196, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "lineno": 143, "outcome": "passed", "keywords": ["test_trainer_registration_mock", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002714149999860638, "outcome": "passed"}, "call": {"duration": 0.021873029999994742, "outcome": "passed"}, "teardown": {"duration": 0.579238192000048, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "lineno": 165, "outcome": "passed", "keywords": ["test_basic_setup", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022734565999996903, "outcome": "passed"}, "call": {"duration": 9.893400005012154e-05, "outcome": "passed"}, "teardown": {"duration": 1.1781732090000219, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "lineno": 170, "outcome": "passed", "keywords": ["test_mock_registration_flow", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022156580999990183, "outcome": "passed"}, "call": {"duration": 0.00019722700000102122, "outcome": "passed"}, "teardown": {"duration": 1.1002410130000158, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_python_version", "lineno": 9, "outcome": "passed", "keywords": ["test_python_version", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00025300100003278203, "outcome": "passed"}, "call": {"duration": 0.00010042700000667537, "outcome": "passed"}, "teardown": {"duration": 0.7226899449999564, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "lineno": 14, "outcome": "passed", "keywords": ["test_can_import_basic_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029348599997547353, "outcome": "passed"}, "call": {"duration": 9.126000003334411e-05, "outcome": "passed"}, "teardown": {"duration": 0.8597835499999746, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_project_structure", "lineno": 28, "outcome": "passed", "keywords": ["test_project_structure", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002489229999582676, "outcome": "passed"}, "call": {"duration": 0.00020241599997916637, "outcome": "passed"}, "teardown": {"duration": 0.5439844710000443, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "lineno": 48, "outcome": "passed", "keywords": ["test_can_import_refiloe_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00023142999998526648, "outcome": "passed"}, "call": {"duration": 0.00041329900000164344, "outcome": "passed"}, "teardown": {"duration": 0.6846891360000313, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_check_requirements", "lineno": 84, "outcome": "passed", "keywords": ["test_check_requirements", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002815839999925629, "outcome": "passed"}, "call": {"duration": 0.07240116899998839, "outcome": "passed"}, "teardown": {"duration": 1.2663882559999706, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "lineno": 77, "outcome": "passed", "keywords": ["test_complete_trainer_registration_flow", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0008361250000348264, "outcome": "passed"}, "call": {"duration": 0.06933676900001728, "outcome": "passed"}, "teardown": {"duration": 0.6705153119999636, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "lineno": 192, "outcome": "passed", "keywords": ["test_currency_parsing_variations", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0008169090000365031, "outcome": "passed"}, "call": {"duration": 0.0001411220000022695, "outcome": "passed"}, "teardown": {"duration": 0.6100242949999597, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "lineno": 211, "outcome": "passed", "keywords": ["test_registration_with_missing_fields", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0007436140000436353, "outcome": "passed"}, "call": {"duration": 0.005369708999978684, "outcome": "passed"}, "teardown": {"duration": 1.2680856430000063, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "lineno": 224, "outcome": "failed", "keywords": ["test_trainer_recognition_after_registration", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0008019219999937377, "outcome": "passed"}, "call": {"duration": 0.7502378770000178, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 253, "message": "AssertionError: assert ('john' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> or 'welcome' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'>)\n +  where <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'>()\n +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>.lower\n +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'> = <built-in method get of dict object at 0x7f3948f278c0>('response', '')\n +        where <built-in method get of dict object at 0x7f3948f278c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\n +  and   <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'>()\n +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>.lower\n +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'> = <built-in method get of dict object at 0x7f3948f278c0>('response', '')\n +        where <built-in method get of dict object at 0x7f3948f278c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 253, "message": "in test_trainer_recognition_after_registration"}], "log": [{"name": "refiloe", "msg": "Background scheduler started", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822545.7904093, "msecs": 790.0, "relativeCreated": 12887.050867080688, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Routes setup complete", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822545.7913609, "msecs": 791.0, "relativeCreated": 12888.002395629883, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822545.8104177, "msecs": 810.0, "relativeCreated": 12907.05919265747, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase1_registration.py:253: in test_trainer_recognition_after_registration\n    assert 'john' in response.get('response', '').lower() or \\\nE   AssertionError: assert ('john' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> or 'welcome' in <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'>)\nE    +  where <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'>()\nE    +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>.lower\nE    +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'> = <built-in method get of dict object at 0x7f3948f278c0>('response', '')\nE    +        where <built-in method get of dict object at 0x7f3948f278c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\nE    +  and   <MagicMock name='AIIntentHandler().generate_smart_response().lower()' id='139884013825360'> = <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'>()\nE    +    where <MagicMock name='AIIntentHandler().generate_smart_response().lower' id='139884013828304'> = <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>.lower\nE    +      where <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'> = <built-in method get of dict object at 0x7f3948f278c0>('response', '')\nE    +        where <built-in method get of dict object at 0x7f3948f278c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "teardown": {"duration": 0.8721494769999936, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "lineno": 281, "outcome": "failed", "keywords": ["test_client_receives_welcome_after_registration", "TestClientRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0032135179999954744, "outcome": "passed"}, "call": {"duration": 0.003630073000010725, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 297, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7f3947dedb80>('success')\n +    where <built-in method get of dict object at 0x7f3947dedb80> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 297, "message": "in test_client_receives_welcome_after_registration"}], "log": [{"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822546.767013, "msecs": 767.0, "relativeCreated": 13863.654613494873, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822546.7697272, "msecs": 769.0, "relativeCreated": 13866.368770599365, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase1_registration.py:297: in test_client_receives_welcome_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7f3947dedb80>('success')\nE    +    where <built-in method get of dict object at 0x7f3947dedb80> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 0.8544632850000085, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "lineno": 311, "outcome": "passed", "keywords": ["test_duplicate_registration_attempt", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005213000000026113, "outcome": "passed"}, "call": {"duration": 0.002663645000041015, "outcome": "passed"}, "teardown": {"duration": 0.5739151759999572, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "lineno": 327, "outcome": "passed", "keywords": ["test_invalid_email_format", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005645500000355241, "outcome": "passed"}, "call": {"duration": 0.00024224100002356863, "outcome": "passed"}, "teardown": {"duration": 0.5452229990000319, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "lineno": 341, "outcome": "passed", "keywords": ["test_extremely_long_input", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006493080000495866, "outcome": "passed"}, "call": {"duration": 8.809400003428891e-05, "outcome": "passed"}, "teardown": {"duration": 0.5091114289999723, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "lineno": 358, "outcome": "passed", "keywords": ["test_special_characters_in_name", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005456960000174149, "outcome": "passed"}, "call": {"duration": 0.00010430399998995199, "outcome": "passed"}, "teardown": {"duration": 0.9956571729999837, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "lineno": 47, "outcome": "passed", "keywords": ["test_add_client_command_variations", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02290965800000322, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822550.2835367, "msecs": 283.0, "relativeCreated": 17380.178213119507, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.01753742500000044, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2844613, "msecs": 284.0, "relativeCreated": 17381.102800369263, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.285272, "msecs": 285.0, "relativeCreated": 17381.913423538208, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2861319, "msecs": 286.0, "relativeCreated": 17382.773399353027, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2864537, "msecs": 286.0, "relativeCreated": 17383.095264434814, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.286673, "msecs": 286.0, "relativeCreated": 17383.314609527588, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2871723, "msecs": 287.0, "relativeCreated": 17383.813858032227, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2874918, "msecs": 287.0, "relativeCreated": 17384.133338928223, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2876737, "msecs": 287.0, "relativeCreated": 17384.315252304077, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2941916, "msecs": 294.0, "relativeCreated": 17390.833139419556, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2945704, "msecs": 294.0, "relativeCreated": 17391.211986541748, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2947528, "msecs": 294.0, "relativeCreated": 17391.39437675476, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2952328, "msecs": 295.0, "relativeCreated": 17391.874313354492, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2956145, "msecs": 295.0, "relativeCreated": 17392.256021499634, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2957747, "msecs": 295.0, "relativeCreated": 17392.41623878479, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2962496, "msecs": 296.0, "relativeCreated": 17392.89116859436, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2966456, "msecs": 296.0, "relativeCreated": 17393.287181854248, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2968152, "msecs": 296.0, "relativeCreated": 17393.45669746399, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.297274, "msecs": 297.0, "relativeCreated": 17393.91565322876, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2975974, "msecs": 297.0, "relativeCreated": 17394.23894882202, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2977788, "msecs": 297.0, "relativeCreated": 17394.420385360718, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2982624, "msecs": 298.0, "relativeCreated": 17394.903898239136, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.298574, "msecs": 298.0, "relativeCreated": 17395.21551132202, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2987492, "msecs": 298.0, "relativeCreated": 17395.39074897766, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.299226, "msecs": 299.0, "relativeCreated": 17395.867586135864, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.2995389, "msecs": 299.0, "relativeCreated": 17396.180391311646, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.299723, "msecs": 299.0, "relativeCreated": 17396.364450454712, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.3002121, "msecs": 300.0, "relativeCreated": 17396.85368537903, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.30052, "msecs": 300.0, "relativeCreated": 17397.16148376465, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.3006976, "msecs": 300.0, "relativeCreated": 17397.33910560608, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822550.301168, "msecs": 301.0, "relativeCreated": 17397.809505462646, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 1.110757279999973, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "lineno": 75, "outcome": "passed", "keywords": ["test_phone_number_normalization", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022974420000025475, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822551.4356089, "msecs": 435.0, "relativeCreated": 18532.25040435791, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.00021514100001240877, "outcome": "passed"}, "teardown": {"duration": 0.744973941000012, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "lineno": 100, "outcome": "passed", "keywords": ["test_add_client_with_special_names", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02341784899999766, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822552.2049415, "msecs": 204.0, "relativeCreated": 19301.58305168152, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.011719783999978972, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2058947, "msecs": 205.0, "relativeCreated": 19302.536249160767, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.206763, "msecs": 206.0, "relativeCreated": 19303.404569625854, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2073684, "msecs": 207.0, "relativeCreated": 19304.009914398193, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2077222, "msecs": 207.0, "relativeCreated": 19304.36372756958, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.207891, "msecs": 207.0, "relativeCreated": 19304.532527923584, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.208397, "msecs": 208.0, "relativeCreated": 19305.038452148438, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2087393, "msecs": 208.0, "relativeCreated": 19305.380821228027, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2089057, "msecs": 208.0, "relativeCreated": 19305.54723739624, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.209396, "msecs": 209.0, "relativeCreated": 19306.037425994873, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2097251, "msecs": 209.0, "relativeCreated": 19306.366682052612, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.209889, "msecs": 209.0, "relativeCreated": 19306.530475616455, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.210375, "msecs": 210.0, "relativeCreated": 19307.016611099243, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2107103, "msecs": 210.0, "relativeCreated": 19307.35182762146, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2108738, "msecs": 210.0, "relativeCreated": 19307.515382766724, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.211339, "msecs": 211.0, "relativeCreated": 19307.98053741455, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.214334, "msecs": 214.0, "relativeCreated": 19310.975551605225, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2151742, "msecs": 215.0, "relativeCreated": 19311.81573867798, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2156901, "msecs": 215.0, "relativeCreated": 19312.331676483154, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2160442, "msecs": 216.0, "relativeCreated": 19312.68572807312, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2162054, "msecs": 216.0, "relativeCreated": 19312.846899032593, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.2167342, "msecs": 216.0, "relativeCreated": 19313.37571144104, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.5733008789999872, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "lineno": 140, "outcome": "failed", "keywords": ["test_view_clients_commands", "TestViewClientsReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000995962999979838, "outcome": "passed"}, "call": {"duration": 0.002882611000018187, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 160, "message": "AssertionError: Failed to list clients with command: Show my clients\nassert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 160, "message": "in test_view_clients_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.7927644, "msecs": 792.0, "relativeCreated": 19889.405965805054, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.793385, "msecs": 793.0, "relativeCreated": 19890.026569366455, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822552.794466, "msecs": 794.0, "relativeCreated": 19891.1075592041, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase2_client_management.py:160: in test_view_clients_commands\n    assert 'sarah' in message or 'john' in message or 'mike' in message or \\\nE   AssertionError: Failed to list clients with command: Show my clients\nE   assert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "teardown": {"duration": 0.5074441999999522, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "lineno": 188, "outcome": "passed", "keywords": ["test_set_custom_pricing_variations", "critical", "pytestmark", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0014614780000101746, "outcome": "passed"}, "call": {"duration": 0.01477614899999935, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3114371, "msecs": 311.0, "relativeCreated": 20408.07867050171, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3120906, "msecs": 312.0, "relativeCreated": 20408.732175827026, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3130076, "msecs": 313.0, "relativeCreated": 20409.64913368225, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3133435, "msecs": 313.0, "relativeCreated": 20409.985065460205, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3135428, "msecs": 313.0, "relativeCreated": 20410.184383392334, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3140626, "msecs": 314.0, "relativeCreated": 20410.704135894775, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.314387, "msecs": 314.0, "relativeCreated": 20411.028623580933, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3145611, "msecs": 314.0, "relativeCreated": 20411.202669143677, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.315123, "msecs": 315.0, "relativeCreated": 20411.76462173462, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3154578, "msecs": 315.0, "relativeCreated": 20412.099361419678, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3156347, "msecs": 315.0, "relativeCreated": 20412.27626800537, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.31612, "msecs": 316.0, "relativeCreated": 20412.761449813843, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3164454, "msecs": 316.0, "relativeCreated": 20413.086891174316, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3166254, "msecs": 316.0, "relativeCreated": 20413.266897201538, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3171308, "msecs": 317.0, "relativeCreated": 20413.772344589233, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3174763, "msecs": 317.0, "relativeCreated": 20414.11781311035, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3177016, "msecs": 317.0, "relativeCreated": 20414.343118667603, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3181841, "msecs": 318.0, "relativeCreated": 20414.825677871704, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3213973, "msecs": 321.0, "relativeCreated": 20418.038845062256, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3216014, "msecs": 321.0, "relativeCreated": 20418.242931365967, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.322106, "msecs": 322.0, "relativeCreated": 20418.747425079346, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3224316, "msecs": 322.0, "relativeCreated": 20419.0731048584, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3226528, "msecs": 322.0, "relativeCreated": 20419.294357299805, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.3231163, "msecs": 323.0, "relativeCreated": 20419.757843017578, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.6704317939999669, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "lineno": 220, "outcome": "failed", "keywords": ["test_check_client_pricing", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.001441250000027594, "outcome": "passed"}, "call": {"duration": 0.0026001049999990755, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 239, "message": "AssertionError: Failed to show pricing with: What is Sarah's rate?\nassert ('r' in '' or 'rand' in '' or False)\n +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7f3948e93760>)"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 239, "message": "in test_check_client_pricing"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.99649, "msecs": 996.0, "relativeCreated": 21093.13154220581, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.9971302, "msecs": 997.0, "relativeCreated": 21093.7716960907, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822553.9981835, "msecs": 998.0, "relativeCreated": 21094.82502937317, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase2_client_management.py:239: in test_check_client_pricing\n    assert 'r' in message or 'rand' in message or \\\nE   AssertionError: Failed to show pricing with: What is Sarah's rate?\nE   assert ('r' in '' or 'rand' in '' or False)\nE    +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7f3948e93760>)"}, "teardown": {"duration": 0.5730224480000174, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "lineno": 253, "outcome": "failed", "keywords": ["test_add_client_with_duplicate_phone", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005570959999658953, "outcome": "passed"}, "call": {"duration": 0.005385595000007015, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 268, "message": "AssertionError: assert ('already' in '' or 'exists' in '')\n +  where '' = <built-in method lower of str object at 0x7f395bb3fba0>()\n +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f3947aad200>('message', '')\n +        where <built-in method get of dict object at 0x7f3947aad200> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\n +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f3947aad200>('message', '')\n +        where <built-in method get of dict object at 0x7f3947aad200> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 268, "message": "in test_add_client_with_duplicate_phone"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822554.5780847, "msecs": 578.0, "relativeCreated": 21674.726247787476, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822554.5809453, "msecs": 580.0, "relativeCreated": 21677.586793899536, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822554.5818589, "msecs": 581.0, "relativeCreated": 21678.500413894653, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase2_client_management.py:268: in test_add_client_with_duplicate_phone\n    assert 'already' in response.get('message', '').lower() or \\\nE   AssertionError: assert ('already' in '' or 'exists' in '')\nE    +  where '' = <built-in method lower of str object at 0x7f395bb3fba0>()\nE    +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f3947aad200>('message', '')\nE    +        where <built-in method get of dict object at 0x7f3947aad200> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\nE    +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f3947aad200>('message', '')\nE    +        where <built-in method get of dict object at 0x7f3947aad200> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "teardown": {"duration": 0.7018428599999993, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "lineno": 270, "outcome": "passed", "keywords": ["test_invalid_phone_numbers", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005083960000433763, "outcome": "passed"}, "call": {"duration": 0.00010351200000968674, "outcome": "passed"}, "teardown": {"duration": 1.1626252390000218, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_negative_pricing", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004915240000400445, "outcome": "passed"}, "call": {"duration": 0.0001070490000074642, "outcome": "passed"}, "teardown": {"duration": 0.7028685020000012, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "lineno": 300, "outcome": "failed", "keywords": ["test_client_not_found", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004567889999975705, "outcome": "passed"}, "call": {"duration": 0.005287492000036309, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 311, "message": "assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\n +  where '' = <built-in method lower of str object at 0x7f395bb3fba0>()\n +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\n +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\n +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\n +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\n +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\n +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 311, "message": "in test_client_not_found"}], "log": [{"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.1610365, "msecs": 161.0, "relativeCreated": 24257.678031921387, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error creating conversation state: 'Mock' object is not subscriptable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.1616788, "msecs": 161.0, "relativeCreated": 24258.320331573486, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.1621237, "msecs": 162.0, "relativeCreated": 24258.76522064209, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase2_client_management.py:311: in test_client_not_found\n    assert 'not found' in response.get('message', '').lower() or \\\nE   assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\nE    +  where '' = <built-in method lower of str object at 0x7f395bb3fba0>()\nE    +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\nE    +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\nE    +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\nE    +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7f395bb3fba0>()\nE    +    where <built-in method lower of str object at 0x7f395bb3fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7f3947ad6080>('message', '')\nE    +        where <built-in method get of dict object at 0x7f3947ad6080> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='139884013702736'>, 'success': True}.get"}, "teardown": {"duration": 0.570367148999992, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "lineno": 53, "outcome": "failed", "keywords": ["test_view_schedule_commands", "TestViewScheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0013042360000099507, "outcome": "passed"}, "call": {"duration": 0.00508310300000403, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 74, "message": "AssertionError: Failed to show schedule with: Show my schedule\nassert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 74, "message": "in test_view_schedule_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.7399275, "msecs": 739.0, "relativeCreated": 24836.56907081604, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.7428768, "msecs": 742.0, "relativeCreated": 24839.518308639526, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822557.743854, "msecs": 743.0, "relativeCreated": 24840.495586395264, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}], "longrepr": "tests/test_phase3_scheduling.py:74: in test_view_schedule_commands\n    assert 'schedule' in message or 'booking' in message or \\\nE   AssertionError: Failed to show schedule with: Show my schedule\nE   assert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "teardown": {"duration": 0.6944283549999568, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "lineno": 110, "outcome": "passed", "keywords": ["test_book_session_natural_language", "critical", "pytestmark", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023624904000030256, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822558.4668312, "msecs": 466.0, "relativeCreated": 25563.472747802734, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.7754585859999565, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKp5eLzCg31kCFo6zE'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKp5eLzCg31kCFo6zE'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.5620604, "msecs": 562.0, "relativeCreated": 25658.70189666748, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpKHXCUHGokmy5k8i'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpKHXCUHGokmy5k8i'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.6214528, "msecs": 621.0, "relativeCreated": 25718.09434890747, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpZAn2eicWJEKRsD2'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpZAn2eicWJEKRsD2'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.6673687, "msecs": 667.0, "relativeCreated": 25764.010190963745, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpjbA6hvbsEJdkwyE'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpjbA6hvbsEJdkwyE'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.7118356, "msecs": 711.0, "relativeCreated": 25808.47716331482, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpuzybLvdfKvAAF4p'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKpuzybLvdfKvAAF4p'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.7517385, "msecs": 751.0, "relativeCreated": 25848.380088806152, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKq7QvfcLh6ij3gcKb'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKq7QvfcLh6ij3gcKb'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.7982857, "msecs": 798.0, "relativeCreated": 25894.927263259888, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKqNXxR93H1kGB39Na'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKqNXxR93H1kGB39Na'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.8828657, "msecs": 882.0, "relativeCreated": 25979.507207870483, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKqjN7dJVQ38mcpezh'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKqjN7dJVQ38mcpezh'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822558.9604654, "msecs": 960.0, "relativeCreated": 26057.106971740723, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKrE8RZsjjGyzX5MDx'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKrE8RZsjjGyzX5MDx'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822559.0642009, "msecs": 64.0, "relativeCreated": 26160.842418670654, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKrYyeLsUHkQQYAvxz'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKrYyeLsUHkQQYAvxz'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822559.1479971, "msecs": 147.0, "relativeCreated": 26244.638681411743, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKs1Wcpaus99JU55ZA'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTVYKs1Wcpaus99JU55ZA'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822559.2419672, "msecs": 241.0, "relativeCreated": 26338.608741760254, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.5125661579999701, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "lineno": 144, "outcome": "passed", "keywords": ["test_booking_time_formats", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023608480999996573, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822559.7794175, "msecs": 779.0, "relativeCreated": 26876.05905532837, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.0014509299999758696, "outcome": "passed"}, "teardown": {"duration": 1.1544120119999661, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "lineno": 169, "outcome": "passed", "keywords": ["test_booking_date_parsing", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023462840999968648, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758822560.959474, "msecs": 959.0, "relativeCreated": 28056.11562728882, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "call": {"duration": 0.0004316799999628529, "outcome": "passed"}, "teardown": {"duration": 0.8532138709999799, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "lineno": 223, "outcome": "passed", "keywords": ["test_cancel_booking_variations", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.003527289999965433, "outcome": "passed"}, "call": {"duration": 0.009187895000025037, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8182487, "msecs": 818.0, "relativeCreated": 28914.89028930664, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8188686, "msecs": 818.0, "relativeCreated": 28915.510177612305, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8198433, "msecs": 819.0, "relativeCreated": 28916.484832763672, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8201716, "msecs": 820.0, "relativeCreated": 28916.813135147095, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8203313, "msecs": 820.0, "relativeCreated": 28916.972875595093, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.820813, "msecs": 820.0, "relativeCreated": 28917.454481124878, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8211656, "msecs": 821.0, "relativeCreated": 28917.80710220337, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.82133, "msecs": 821.0, "relativeCreated": 28917.97161102295, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8218, "msecs": 821.0, "relativeCreated": 28918.44153404236, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8221204, "msecs": 822.0, "relativeCreated": 28918.76196861267, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8223522, "msecs": 822.0, "relativeCreated": 28918.993711471558, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8228314, "msecs": 822.0, "relativeCreated": 28919.47293281555, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8231504, "msecs": 823.0, "relativeCreated": 28919.79193687439, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.823318, "msecs": 823.0, "relativeCreated": 28919.959545135498, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8238287, "msecs": 823.0, "relativeCreated": 28920.470237731934, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8241343, "msecs": 824.0, "relativeCreated": 28920.77589035034, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8243022, "msecs": 824.0, "relativeCreated": 28920.94373703003, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.824778, "msecs": 824.0, "relativeCreated": 28921.419620513916, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.825084, "msecs": 825.0, "relativeCreated": 28921.725511550903, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.825238, "msecs": 825.0, "relativeCreated": 28921.879529953003, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8256893, "msecs": 825.0, "relativeCreated": 28922.330856323242, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.826019, "msecs": 826.0, "relativeCreated": 28922.66058921814, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.826174, "msecs": 826.0, "relativeCreated": 28922.815561294556, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822561.8266323, "msecs": 826.0, "relativeCreated": 28923.27380180359, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.7015242069999772, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "lineno": 248, "outcome": "passed", "keywords": ["test_reschedule_booking", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0010800780000295163, "outcome": "passed"}, "call": {"duration": 0.010880528000029699, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.530615, "msecs": 530.0, "relativeCreated": 29627.256631851196, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5312028, "msecs": 531.0, "relativeCreated": 29627.84433364868, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5321493, "msecs": 532.0, "relativeCreated": 29628.790855407715, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.532472, "msecs": 532.0, "relativeCreated": 29629.11343574524, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.532658, "msecs": 532.0, "relativeCreated": 29629.299640655518, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5379734, "msecs": 537.0, "relativeCreated": 29634.614944458008, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5382836, "msecs": 538.0, "relativeCreated": 29634.92512702942, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5384405, "msecs": 538.0, "relativeCreated": 29635.082006454468, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5388927, "msecs": 538.0, "relativeCreated": 29635.534286499023, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5392113, "msecs": 539.0, "relativeCreated": 29635.852813720703, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5393534, "msecs": 539.0, "relativeCreated": 29635.994911193848, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5398343, "msecs": 539.0, "relativeCreated": 29636.475801467896, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5401394, "msecs": 540.0, "relativeCreated": 29636.780977249146, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.5403056, "msecs": 540.0, "relativeCreated": 29636.94715499878, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822562.540742, "msecs": 540.0, "relativeCreated": 29637.383460998535, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.5352323609999985, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "lineno": 283, "outcome": "passed", "keywords": ["test_double_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004683610000029148, "outcome": "passed"}, "call": {"duration": 0.002801260000012462, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822563.0799344, "msecs": 79.0, "relativeCreated": 30176.575899124146, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.6974787830000082, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "lineno": 313, "outcome": "passed", "keywords": ["test_past_date_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00047949100002142586, "outcome": "passed"}, "call": {"duration": 0.001237271000036344, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758822563.779698, "msecs": 779.0, "relativeCreated": 30876.339435577393, "thread": 139884329601920, "threadName": "MainThread", "processName": "MainProcess", "process": 2202}]}, "teardown": {"duration": 0.5851276129999974, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "lineno": 334, "outcome": "passed", "keywords": ["test_invalid_time_slots", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004914340000254924, "outcome": "passed"}, "call": {"duration": 0.0005049389999953746, "outcome": "passed"}, "teardown": {"duration": 0.4910567599999922, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "lineno": 227, "outcome": "passed", "keywords": ["test_new_trainer_onboarding", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00025968300002432443, "outcome": "passed"}, "call": {"duration": 0.0040218910000362484, "outcome": "passed"}, "teardown": {"duration": 0.5216356199999836, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "lineno": 242, "outcome": "passed", "keywords": ["test_trainer_recognition", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00034809800001767144, "outcome": "passed"}, "call": {"duration": 0.0028593989999876612, "outcome": "passed"}, "teardown": {"duration": 1.0243193079999742, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "lineno": 269, "outcome": "passed", "keywords": ["test_add_client_variations", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00033562400000164416, "outcome": "passed"}, "call": {"duration": 0.00480558800001063, "outcome": "passed"}, "teardown": {"duration": 0.720764384000006, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "lineno": 278, "outcome": "passed", "keywords": ["test_view_clients", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031183999999484513, "outcome": "passed"}, "call": {"duration": 0.002699340999981814, "outcome": "passed"}, "teardown": {"duration": 0.5580169219999789, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_custom_pricing", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031192999995255377, "outcome": "passed"}, "call": {"duration": 0.004166439000016453, "outcome": "passed"}, "teardown": {"duration": 0.49502588100000366, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "lineno": 299, "outcome": "passed", "keywords": ["test_view_schedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00026693699999214004, "outcome": "passed"}, "call": {"duration": 0.0025923829999783266, "outcome": "passed"}, "teardown": {"duration": 0.8510781830000269, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "lineno": 308, "outcome": "passed", "keywords": ["test_book_sessions", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00028596199996400173, "outcome": "passed"}, "call": {"duration": 0.004187220999995134, "outcome": "passed"}, "teardown": {"duration": 0.5716058500000258, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "lineno": 317, "outcome": "failed", "keywords": ["test_cancel_reschedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002374819999886313, "outcome": "passed"}, "call": {"duration": 0.006976770999983728, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 329, "message": "assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\n +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f39581708f0>()\n +    where <built-in method lower of str object at 0x7f39581708f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\n +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f39581708f0>()\n +    where <built-in method lower of str object at 0x7f39581708f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 329, "message": "in test_cancel_reschedule"}], "longrepr": "tests/test_refiloe_complete.py:329: in test_cancel_reschedule\n    assert \"reschedul\" in response['message'].lower() or \"moved\" in response['message'].lower()\nE   assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\nE    +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f39581708f0>()\nE    +    where <built-in method lower of str object at 0x7f39581708f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\nE    +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7f39581708f0>()\nE    +    where <built-in method lower of str object at 0x7f39581708f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "teardown": {"duration": 0.6833093760000111, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "lineno": 334, "outcome": "passed", "keywords": ["test_setup_habits", "TestPhase4_HabitTracking", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002523989999758669, "outcome": "passed"}, "call": {"duration": 0.004188783000017793, "outcome": "passed"}, "teardown": {"duration": 0.8254946360000304, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "lineno": 347, "outcome": "passed", "keywords": ["test_send_workouts", "TestPhase5_WorkoutsAssessments", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002558759999828908, "outcome": "passed"}, "call": {"duration": 0.004499721000001955, "outcome": "passed"}, "teardown": {"duration": 0.6782563550000305, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "lineno": 360, "outcome": "failed", "keywords": ["test_request_payment", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00023233299998537404, "outcome": "passed"}, "call": {"duration": 0.004772679999973661, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 368, "message": "assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\n +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f395817a150>()\n +    where <built-in method lower of str object at 0x7f395817a150> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\n +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f395817a150>()\n +    where <built-in method lower of str object at 0x7f395817a150> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 368, "message": "in test_request_payment"}], "longrepr": "tests/test_refiloe_complete.py:368: in test_request_payment\n    assert \"payment\" in response['message'].lower() or \"invoice\" in response['message'].lower()\nE   assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\nE    +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f395817a150>()\nE    +    where <built-in method lower of str object at 0x7f395817a150> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\nE    +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7f395817a150>()\nE    +    where <built-in method lower of str object at 0x7f395817a150> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "teardown": {"duration": 0.7870345260000136, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "lineno": 369, "outcome": "passed", "keywords": ["test_check_revenue", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002938869999979943, "outcome": "passed"}, "call": {"duration": 0.004229367999982969, "outcome": "passed"}, "teardown": {"duration": 0.5380526960000225, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "lineno": 381, "outcome": "passed", "keywords": ["test_client_booking", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029637200003662656, "outcome": "passed"}, "call": {"duration": 0.004650872999945932, "outcome": "passed"}, "teardown": {"duration": 0.5078870230000234, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "lineno": 390, "outcome": "passed", "keywords": ["test_client_habit_logging", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002736289999916153, "outcome": "passed"}, "call": {"duration": 0.004591591999997036, "outcome": "passed"}, "teardown": {"duration": 0.6944034239999723, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "lineno": 403, "outcome": "passed", "keywords": ["test_natural_language_understanding", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003034840000282202, "outcome": "passed"}, "call": {"duration": 0.004350001999966935, "outcome": "passed"}, "teardown": {"duration": 0.6849004150000155, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "lineno": 412, "outcome": "failed", "keywords": ["test_error_handling", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002961409999784337, "outcome": "passed"}, "call": {"duration": 0.0027307410000503296, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 424, "message": "assert False\n +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7f3947de8820>)"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 424, "message": "in test_error_handling"}], "longrepr": "tests/test_refiloe_complete.py:424: in test_error_handling\n    assert any(word in response['message'].lower() for word in [\"past\", \"future\", \"cannot\"])\nE   assert False\nE    +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7f3947de8820>)"}, "teardown": {"duration": 0.5118988440000294, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "lineno": 433, "outcome": "passed", "keywords": ["test_trainer_registration_step_7_currency_parsing", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031487500001503577, "outcome": "passed"}, "call": {"duration": 0.0006626830000300288, "outcome": "passed"}, "teardown": {"duration": 0.6598340019999682, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "lineno": 457, "outcome": "passed", "keywords": ["test_ai_responds_naturally_not_rigid_commands", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00026553399999329486, "outcome": "passed"}, "call": {"duration": 0.007248469000046498, "outcome": "passed"}, "teardown": {"duration": 0.8147384060000036, "outcome": "passed"}}], "warnings": [{"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "\nPyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),\n(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)\nbut was not found to be installed on your system.\nIf this would cause problems for you,\nplease provide us feedback at https://github.com/pandas-dev/pandas/issues/54466\n        ", "category": "DeprecationWarning", "when": "runtest", "filename": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/analytics.py", "lineno": 7}]}