{"created": 1758576917.9393747, "duration": 39.77504229545593, "exitcode": 1, "root": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant", "environment": {}, "summary": {"passed": 43, "failed": 13, "total": 56, "collected": 56}, "collectors": [{"nodeid": "", "outcome": "passed", "result": [{"nodeid": "tests/__init__.py", "type": "Package"}]}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "type": "Function", "lineno": 130}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "type": "Function", "lineno": 136}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "type": "Function", "lineno": 143}]}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "type": "Function", "lineno": 165}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "type": "Function", "lineno": 170}]}, {"nodeid": "tests/test_conversation_flows.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality", "type": "Class"}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration", "type": "Class"}]}, {"nodeid": "tests/test_debug.py", "outcome": "passed", "result": [{"nodeid": "tests/test_debug.py::test_python_version", "type": "Function", "lineno": 9}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "type": "Function", "lineno": 14}, {"nodeid": "tests/test_debug.py::test_project_structure", "type": "Function", "lineno": 28}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "type": "Function", "lineno": 48}, {"nodeid": "tests/test_debug.py::test_check_requirements", "type": "Function", "lineno": 84}]}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "type": "Function", "lineno": 56}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "type": "Function", "lineno": 141}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "type": "Function", "lineno": 160}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "type": "Function", "lineno": 173}]}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "type": "Function", "lineno": 230}]}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "type": "Function", "lineno": 260}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "type": "Function", "lineno": 276}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "type": "Function", "lineno": 290}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "type": "Function", "lineno": 307}]}, {"nodeid": "tests/test_phase1_registration.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal", "type": "Class"}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "type": "Function", "lineno": 47}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "type": "Function", "lineno": 75}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "type": "Function", "lineno": 100}]}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "type": "Function", "lineno": 140}]}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "type": "Function", "lineno": 188}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "type": "Function", "lineno": 220}]}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "type": "Function", "lineno": 253}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "type": "Function", "lineno": 270}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "type": "Function", "lineno": 286}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "type": "Function", "lineno": 300}]}, {"nodeid": "tests/test_phase2_client_management.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal", "type": "Class"}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases", "type": "Class"}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "type": "Function", "lineno": 53}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "type": "Function", "lineno": 110}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "type": "Function", "lineno": 144}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "type": "Function", "lineno": 169}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "type": "Function", "lineno": 223}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "type": "Function", "lineno": 248}]}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "type": "Function", "lineno": 283}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "type": "Function", "lineno": 313}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_phase3_scheduling.py", "outcome": "passed", "result": [{"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal", "type": "Class"}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation", "type": "Class"}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "type": "Function", "lineno": 227}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "type": "Function", "lineno": 242}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "type": "Function", "lineno": 269}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "type": "Function", "lineno": 278}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "type": "Function", "lineno": 286}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "type": "Function", "lineno": 299}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "type": "Function", "lineno": 308}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "type": "Function", "lineno": 317}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "type": "Function", "lineno": 334}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "type": "Function", "lineno": 347}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "type": "Function", "lineno": 360}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "type": "Function", "lineno": 369}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "type": "Function", "lineno": 381}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "type": "Function", "lineno": 390}]}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "type": "Function", "lineno": 403}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "type": "Function", "lineno": 412}]}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "type": "Function", "lineno": 433}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "type": "Function", "lineno": 457}]}, {"nodeid": "tests/test_refiloe_complete.py", "outcome": "passed", "result": [{"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures", "type": "Class"}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs", "type": "Class"}]}, {"nodeid": "tests/__init__.py", "outcome": "passed", "result": [{"nodeid": "tests/test_conversation_flows.py", "type": "Module"}, {"nodeid": "tests/test_debug.py", "type": "Module"}, {"nodeid": "tests/test_phase1_registration.py", "type": "Module"}, {"nodeid": "tests/test_phase2_client_management.py", "type": "Module"}, {"nodeid": "tests/test_phase3_scheduling.py", "type": "Module"}, {"nodeid": "tests/test_refiloe_complete.py", "type": "Module"}]}], "tests": [{"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_imports_work", "lineno": 130, "outcome": "passed", "keywords": ["test_imports_work", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005308789999958208, "outcome": "passed"}, "call": {"duration": 0.03298938400000395, "outcome": "passed"}, "teardown": {"duration": 0.7088746530000094, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_mock_message", "lineno": 136, "outcome": "passed", "keywords": ["test_mock_message", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00038695100001007177, "outcome": "passed"}, "call": {"duration": 0.021793657999992888, "outcome": "passed"}, "teardown": {"duration": 0.5588220600000113, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestBasicFunctionality::test_trainer_registration_mock", "lineno": 143, "outcome": "passed", "keywords": ["test_trainer_registration_mock", "TestBasicFunctionality", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003800070000039568, "outcome": "passed"}, "call": {"duration": 0.02230306600000631, "outcome": "passed"}, "teardown": {"duration": 0.842046737000004, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_basic_setup", "lineno": 165, "outcome": "passed", "keywords": ["test_basic_setup", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02286762699999656, "outcome": "passed"}, "call": {"duration": 0.00010296100001028208, "outcome": "passed"}, "teardown": {"duration": 1.2201158419999985, "outcome": "passed"}}, {"nodeid": "tests/test_conversation_flows.py::TestPhase1_Registration::test_mock_registration_flow", "lineno": 170, "outcome": "passed", "keywords": ["test_mock_registration_flow", "TestPhase1_Registration", "test_conversation_flows.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022095440000001076, "outcome": "passed"}, "call": {"duration": 0.00021978899999908208, "outcome": "passed"}, "teardown": {"duration": 0.8341282389999947, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_python_version", "lineno": 9, "outcome": "passed", "keywords": ["test_python_version", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003351539999982833, "outcome": "passed"}, "call": {"duration": 0.00010404299999322575, "outcome": "passed"}, "teardown": {"duration": 0.5754066229999921, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_basic_modules", "lineno": 14, "outcome": "passed", "keywords": ["test_can_import_basic_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003080639999950563, "outcome": "passed"}, "call": {"duration": 9.074900000882735e-05, "outcome": "passed"}, "teardown": {"duration": 0.6922792639999784, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_project_structure", "lineno": 28, "outcome": "passed", "keywords": ["test_project_structure", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031131899999081725, "outcome": "passed"}, "call": {"duration": 0.0002378329999999096, "outcome": "passed"}, "teardown": {"duration": 0.5377895260000116, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_can_import_refiloe_modules", "lineno": 48, "outcome": "passed", "keywords": ["test_can_import_refiloe_modules", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029201399999578825, "outcome": "passed"}, "call": {"duration": 0.0004207329999985632, "outcome": "passed"}, "teardown": {"duration": 0.6773300410000047, "outcome": "passed"}}, {"nodeid": "tests/test_debug.py::test_check_requirements", "lineno": 84, "outcome": "passed", "keywords": ["test_check_requirements", "test_debug.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003131720000055793, "outcome": "passed"}, "call": {"duration": 0.07401392299999543, "outcome": "passed"}, "teardown": {"duration": 0.5071433690000049, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_complete_trainer_registration_flow", "lineno": 56, "outcome": "failed", "keywords": ["test_complete_trainer_registration_flow", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.004192163999988452, "outcome": "passed"}, "call": {"duration": 0.0006805969999845729, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 72, "message": "assert 'step 1' in \"welcome back, there! you're already registered. how can i help you today?\"\n +  where \"welcome back, there! you're already registered. how can i help you today?\" = <built-in method lower of str object at 0x7fd43a561eb0>()\n +    where <built-in method lower of str object at 0x7fd43a561eb0> = \"Welcome back, there! You're already registered. How can I help you today?\".lower"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 72, "message": "in test_complete_trainer_registration_flow"}], "longrepr": "tests/test_phase1_registration.py:72: in test_complete_trainer_registration_flow\n    assert \"step 1\" in response.lower()\nE   assert 'step 1' in \"welcome back, there! you're already registered. how can i help you today?\"\nE    +  where \"welcome back, there! you're already registered. how can i help you today?\" = <built-in method lower of str object at 0x7fd43a561eb0>()\nE    +    where <built-in method lower of str object at 0x7fd43a561eb0> = \"Welcome back, there! You're already registered. How can I help you today?\".lower"}, "teardown": {"duration": 1.2739341829999944, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_currency_parsing_variations", "lineno": 141, "outcome": "passed", "keywords": ["test_currency_parsing_variations", "critical", "pytestmark", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0038236439999934646, "outcome": "passed"}, "call": {"duration": 0.0004734219999988909, "outcome": "passed"}, "teardown": {"duration": 0.5247278079999944, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_registration_with_missing_fields", "lineno": 160, "outcome": "passed", "keywords": ["test_registration_with_missing_fields", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.002191299000003255, "outcome": "passed"}, "call": {"duration": 0.0003134030000069288, "outcome": "passed"}, "teardown": {"duration": 0.6597339989999966, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestTrainerRegistrationReal::test_trainer_recognition_after_registration", "lineno": 173, "outcome": "failed", "keywords": ["test_trainer_recognition_after_registration", "TestTrainerRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0017609779999929742, "outcome": "passed"}, "call": {"duration": 0.9676264480000043, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 201, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7fd42b6963c0>('success')\n +    where <built-in method get of dict object at 0x7fd42b6963c0> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 201, "message": "in test_trainer_recognition_after_registration"}], "log": [{"name": "refiloe", "msg": "Background scheduler started", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576889.4351623, "msecs": 435.0, "relativeCreated": 12267.679929733276, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Routes setup complete", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576889.4361348, "msecs": 436.0, "relativeCreated": 12268.652439117432, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576889.441073, "msecs": 441.0, "relativeCreated": 12273.590564727783, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576889.44271, "msecs": 442.0, "relativeCreated": 12275.227546691895, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase1_registration.py:201: in test_trainer_recognition_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7fd42b6963c0>('success')\nE    +    where <built-in method get of dict object at 0x7fd42b6963c0> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 0.5766999020000014, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestClientRegistrationReal::test_client_receives_welcome_after_registration", "lineno": 230, "outcome": "failed", "keywords": ["test_client_receives_welcome_after_registration", "TestClientRegistrationReal", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0035219960000176798, "outcome": "passed"}, "call": {"duration": 0.0041244479999988926, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase1_registration.py", "lineno": 246, "message": "assert False == True\n +  where False = <built-in method get of dict object at 0x7fd42b729b40>('success')\n +    where <built-in method get of dict object at 0x7fd42b729b40> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "traceback": [{"path": "tests/test_phase1_registration.py", "lineno": 246, "message": "in test_client_receives_welcome_after_registration"}], "log": [{"name": "refiloe", "msg": "Error getting user context: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576890.0300384, "msecs": 30.0, "relativeCreated": 12862.555980682373, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error handling message: 'list' object has no attribute 'get'", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576890.0323668, "msecs": 32.0, "relativeCreated": 12864.884376525879, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase1_registration.py:246: in test_client_receives_welcome_after_registration\n    assert response.get('success') == True\nE   assert False == True\nE    +  where False = <built-in method get of dict object at 0x7fd42b729b40>('success')\nE    +    where <built-in method get of dict object at 0x7fd42b729b40> = {'response': \"Sorry, I'm having a bit of trouble right now. Please try again in a moment! \ud83d\ude0a\", 'success': False}.get"}, "teardown": {"duration": 0.5483343809999894, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_duplicate_registration_attempt", "lineno": 260, "outcome": "passed", "keywords": ["test_duplicate_registration_attempt", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005706819999886648, "outcome": "passed"}, "call": {"duration": 0.003203412000004846, "outcome": "passed"}, "teardown": {"duration": 0.5483746280000048, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_invalid_email_format", "lineno": 276, "outcome": "passed", "keywords": ["test_invalid_email_format", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0006397410000147374, "outcome": "passed"}, "call": {"duration": 0.00027375999999890155, "outcome": "passed"}, "teardown": {"duration": 0.6944374740000114, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_extremely_long_input", "lineno": 290, "outcome": "passed", "keywords": ["test_extremely_long_input", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005844190000061644, "outcome": "passed"}, "call": {"duration": 9.261200000310055e-05, "outcome": "passed"}, "teardown": {"duration": 0.5459077940000157, "outcome": "passed"}}, {"nodeid": "tests/test_phase1_registration.py::TestRegistrationEdgeCases::test_special_characters_in_name", "lineno": 307, "outcome": "passed", "keywords": ["test_special_characters_in_name", "TestRegistrationEdgeCases", "test_phase1_registration.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000638038000005281, "outcome": "passed"}, "call": {"duration": 9.452599999804079e-05, "outcome": "passed"}, "teardown": {"duration": 1.0752134440000134, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_command_variations", "lineno": 47, "outcome": "passed", "keywords": ["test_add_client_command_variations", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022782577999976183, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576893.4806073, "msecs": 480.0, "relativeCreated": 16313.124895095825, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.018759893000009242, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4815528, "msecs": 481.0, "relativeCreated": 16314.070463180542, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4823062, "msecs": 482.0, "relativeCreated": 16314.823865890503, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.483966, "msecs": 483.0, "relativeCreated": 16316.483736038208, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4843175, "msecs": 484.0, "relativeCreated": 16316.835165023804, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4844885, "msecs": 484.0, "relativeCreated": 16317.00611114502, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.491289, "msecs": 491.0, "relativeCreated": 16323.806524276733, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4916842, "msecs": 491.0, "relativeCreated": 16324.201822280884, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4918501, "msecs": 491.0, "relativeCreated": 16324.367761611938, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4923623, "msecs": 492.0, "relativeCreated": 16324.879884719849, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4927135, "msecs": 492.0, "relativeCreated": 16325.231075286865, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4928758, "msecs": 492.0, "relativeCreated": 16325.393438339233, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4933915, "msecs": 493.0, "relativeCreated": 16325.90913772583, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.493712, "msecs": 493.0, "relativeCreated": 16326.229572296143, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4938996, "msecs": 493.0, "relativeCreated": 16326.417207717896, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4944096, "msecs": 494.0, "relativeCreated": 16326.927185058594, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4947422, "msecs": 494.0, "relativeCreated": 16327.25977897644, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.49491, "msecs": 494.0, "relativeCreated": 16327.427625656128, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4954467, "msecs": 495.0, "relativeCreated": 16327.964305877686, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4957726, "msecs": 495.0, "relativeCreated": 16328.290224075317, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4959402, "msecs": 495.0, "relativeCreated": 16328.457832336426, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4964583, "msecs": 496.0, "relativeCreated": 16328.975915908813, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4967754, "msecs": 496.0, "relativeCreated": 16329.293012619019, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4969392, "msecs": 496.0, "relativeCreated": 16329.456806182861, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4974844, "msecs": 497.0, "relativeCreated": 16330.002069473267, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4978127, "msecs": 497.0, "relativeCreated": 16330.33037185669, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.497996, "msecs": 497.0, "relativeCreated": 16330.513715744019, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.498464, "msecs": 498.0, "relativeCreated": 16330.981731414795, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.4988067, "msecs": 498.0, "relativeCreated": 16331.324338912964, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.498993, "msecs": 498.0, "relativeCreated": 16331.510543823242, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576893.499456, "msecs": 499.0, "relativeCreated": 16331.973552703857, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.5165951820000032, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_phone_number_normalization", "lineno": 75, "outcome": "failed", "keywords": ["test_phone_number_normalization", "critical", "pytestmark", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022720703000004505, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576894.0393932, "msecs": 39.0, "relativeCreated": 16871.91081047058, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.000401477000025352, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 98, "message": "AssertionError: Expected 27821234567 but got +27821234567 for 0821234567\nassert '+27821234567' == '27821234567'\n  - 27821234567\n  + +27821234567\n  ? +"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 98, "message": "in test_phone_number_normalization"}], "longrepr": "tests/test_phase2_client_management.py:98: in test_phone_number_normalization\n    assert normalized == expected_phone, \\\nE   AssertionError: Expected 27821234567 but got +27821234567 for 0821234567\nE   assert '+27821234567' == '27821234567'\nE     - 27821234567\nE     + +27821234567\nE     ? +"}, "teardown": {"duration": 1.013384134000006, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestAddClientReal::test_add_client_with_special_names", "lineno": 100, "outcome": "passed", "keywords": ["test_add_client_with_special_names", "TestAddClientReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.022773401999984344, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576895.0808954, "msecs": 80.0, "relativeCreated": 17913.413047790527, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.050267749999989064, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0837913, "msecs": 83.0, "relativeCreated": 17916.308879852295, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0844111, "msecs": 84.0, "relativeCreated": 17916.92876815796, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0850217, "msecs": 85.0, "relativeCreated": 17917.539358139038, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.085332, "msecs": 85.0, "relativeCreated": 17917.84954071045, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0882845, "msecs": 88.0, "relativeCreated": 17920.802116394043, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0893924, "msecs": 89.0, "relativeCreated": 17921.910047531128, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.089696, "msecs": 89.0, "relativeCreated": 17922.213554382324, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.0898445, "msecs": 89.0, "relativeCreated": 17922.362089157104, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.127555, "msecs": 127.0, "relativeCreated": 17960.07251739502, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1279173, "msecs": 127.0, "relativeCreated": 17960.434913635254, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1280951, "msecs": 128.0, "relativeCreated": 17960.612773895264, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1285584, "msecs": 128.0, "relativeCreated": 17961.076021194458, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1288521, "msecs": 128.0, "relativeCreated": 17961.36975288391, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1290195, "msecs": 129.0, "relativeCreated": 17961.53712272644, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1294787, "msecs": 129.0, "relativeCreated": 17961.99631690979, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1297677, "msecs": 129.0, "relativeCreated": 17962.28528022766, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1299176, "msecs": 129.0, "relativeCreated": 17962.435245513916, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1303623, "msecs": 130.0, "relativeCreated": 17962.87989616394, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1306741, "msecs": 130.0, "relativeCreated": 17963.191747665405, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1308215, "msecs": 130.0, "relativeCreated": 17963.33909034729, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.1312587, "msecs": 131.0, "relativeCreated": 17963.776350021362, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.6920680319999803, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestViewClientsReal::test_view_clients_commands", "lineno": 140, "outcome": "failed", "keywords": ["test_view_clients_commands", "TestViewClientsReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0009487859999808279, "outcome": "passed"}, "call": {"duration": 0.0028819930000167915, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 160, "message": "AssertionError: Failed to list clients with command: Show my clients\nassert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 160, "message": "in test_view_clients_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.826168, "msecs": 826.0, "relativeCreated": 18658.6856842041, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.8267756, "msecs": 826.0, "relativeCreated": 18659.293174743652, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576895.827731, "msecs": 827.0, "relativeCreated": 18660.248517990112, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase2_client_management.py:160: in test_view_clients_commands\n    assert 'sarah' in message or 'john' in message or 'mike' in message or \\\nE   AssertionError: Failed to list clients with command: Show my clients\nE   assert ('sarah' in '' or 'john' in '' or 'mike' in '' or 'client' in '')"}, "teardown": {"duration": 0.47856795900000293, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_set_custom_pricing_variations", "lineno": 188, "outcome": "passed", "keywords": ["test_set_custom_pricing_variations", "critical", "pytestmark", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0013663729999962015, "outcome": "passed"}, "call": {"duration": 0.013892915000013772, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3154504, "msecs": 315.0, "relativeCreated": 19147.96805381775, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.316087, "msecs": 316.0, "relativeCreated": 19148.60463142395, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3169975, "msecs": 316.0, "relativeCreated": 19149.51515197754, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3173718, "msecs": 317.0, "relativeCreated": 19149.88946914673, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.317531, "msecs": 317.0, "relativeCreated": 19150.04873275757, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3180156, "msecs": 318.0, "relativeCreated": 19150.533199310303, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.318352, "msecs": 318.0, "relativeCreated": 19150.869607925415, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3209875, "msecs": 320.0, "relativeCreated": 19153.505086898804, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.321493, "msecs": 321.0, "relativeCreated": 19154.0105342865, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3218186, "msecs": 321.0, "relativeCreated": 19154.33621406555, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3219962, "msecs": 321.0, "relativeCreated": 19154.513835906982, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3224773, "msecs": 322.0, "relativeCreated": 19154.99496459961, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3227992, "msecs": 322.0, "relativeCreated": 19155.316829681396, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3229742, "msecs": 322.0, "relativeCreated": 19155.491828918457, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3234317, "msecs": 323.0, "relativeCreated": 19155.949354171753, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3237689, "msecs": 323.0, "relativeCreated": 19156.286478042603, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3239317, "msecs": 323.0, "relativeCreated": 19156.44931793213, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3244047, "msecs": 324.0, "relativeCreated": 19156.922340393066, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3247924, "msecs": 324.0, "relativeCreated": 19157.310009002686, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.324973, "msecs": 324.0, "relativeCreated": 19157.490730285645, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3254263, "msecs": 325.0, "relativeCreated": 19157.943964004517, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3257434, "msecs": 325.0, "relativeCreated": 19158.26106071472, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.325921, "msecs": 325.0, "relativeCreated": 19158.438682556152, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576896.3263798, "msecs": 326.0, "relativeCreated": 19158.897399902344, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.8508194309999908, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestCustomPricingReal::test_check_client_pricing", "lineno": 220, "outcome": "failed", "keywords": ["test_check_client_pricing", "TestCustomPricingReal", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0013540399999953934, "outcome": "passed"}, "call": {"duration": 0.0025059429999885197, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 239, "message": "AssertionError: Failed to show pricing with: What is Sarah's rate?\nassert ('r' in '' or 'rand' in '' or False)\n +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7fd42b68edc0>)"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 239, "message": "in test_check_client_pricing"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.1799695, "msecs": 179.0, "relativeCreated": 20012.487173080444, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.1805875, "msecs": 180.0, "relativeCreated": 20013.105154037476, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.18158, "msecs": 181.0, "relativeCreated": 20014.097690582275, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase2_client_management.py:239: in test_check_client_pricing\n    assert 'r' in message or 'rand' in message or \\\nE   AssertionError: Failed to show pricing with: What is Sarah's rate?\nE   assert ('r' in '' or 'rand' in '' or False)\nE    +  where False = any(<generator object TestCustomPricingReal.test_check_client_pricing.<locals>.<genexpr> at 0x7fd42b68edc0>)"}, "teardown": {"duration": 0.4962587910000025, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_add_client_with_duplicate_phone", "lineno": 253, "outcome": "failed", "keywords": ["test_add_client_with_duplicate_phone", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00046538600000189945, "outcome": "passed"}, "call": {"duration": 0.005180862000003117, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 268, "message": "AssertionError: assert ('already' in '' or 'exists' in '')\n +  where '' = <built-in method lower of str object at 0x7fd43e33fba0>()\n +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fd43a5ec5c0>('message', '')\n +        where <built-in method get of dict object at 0x7fd43a5ec5c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\n +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fd43a5ec5c0>('message', '')\n +        where <built-in method get of dict object at 0x7fd43a5ec5c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 268, "message": "in test_add_client_with_duplicate_phone"}], "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.6844347, "msecs": 684.0, "relativeCreated": 20516.95227622986, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.6871455, "msecs": 687.0, "relativeCreated": 20519.663095474243, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576897.6880512, "msecs": 688.0, "relativeCreated": 20520.56884765625, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase2_client_management.py:268: in test_add_client_with_duplicate_phone\n    assert 'already' in response.get('message', '').lower() or \\\nE   AssertionError: assert ('already' in '' or 'exists' in '')\nE    +  where '' = <built-in method lower of str object at 0x7fd43e33fba0>()\nE    +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fd43a5ec5c0>('message', '')\nE    +        where <built-in method get of dict object at 0x7fd43a5ec5c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\nE    +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fd43a5ec5c0>('message', '')\nE    +        where <built-in method get of dict object at 0x7fd43a5ec5c0> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get"}, "teardown": {"duration": 0.49298221500001205, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_invalid_phone_numbers", "lineno": 270, "outcome": "passed", "keywords": ["test_invalid_phone_numbers", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000463042000006908, "outcome": "passed"}, "call": {"duration": 0.00010453500001972316, "outcome": "passed"}, "teardown": {"duration": 0.5096069420000049, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_set_negative_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_negative_pricing", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004114850000007664, "outcome": "passed"}, "call": {"duration": 0.00010053700000867138, "outcome": "passed"}, "teardown": {"duration": 0.4822724429999994, "outcome": "passed"}}, {"nodeid": "tests/test_phase2_client_management.py::TestClientManagementEdgeCases::test_client_not_found", "lineno": 300, "outcome": "failed", "keywords": ["test_client_not_found", "TestClientManagementEdgeCases", "test_phase2_client_management.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004348889999903349, "outcome": "passed"}, "call": {"duration": 0.004672295000005988, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase2_client_management.py", "lineno": 311, "message": "assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\n +  where '' = <built-in method lower of str object at 0x7fd43e33fba0>()\n +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\n +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\n +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\n +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\n +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\n +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\n +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\n +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get"}, "traceback": [{"path": "tests/test_phase2_client_management.py", "lineno": 311, "message": "in test_client_not_found"}], "log": [{"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.1865983, "msecs": 186.0, "relativeCreated": 22019.115924835205, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error creating conversation state: 'Mock' object is not subscriptable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.1872153, "msecs": 187.0, "relativeCreated": 22019.73295211792, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.1876411, "msecs": 187.0, "relativeCreated": 22020.158767700195, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase2_client_management.py:311: in test_client_not_found\n    assert 'not found' in response.get('message', '').lower() or \\\nE   assert ('not found' in '' or \"doesn't exist\" in '' or 'no client' in '')\nE    +  where '' = <built-in method lower of str object at 0x7fd43e33fba0>()\nE    +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\nE    +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\nE    +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\nE    +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get\nE    +  and   '' = <built-in method lower of str object at 0x7fd43e33fba0>()\nE    +    where <built-in method lower of str object at 0x7fd43e33fba0> = ''.lower\nE    +      where '' = <built-in method get of dict object at 0x7fd42b681900>('message', '')\nE    +        where <built-in method get of dict object at 0x7fd42b681900> = {'response': <MagicMock name='AIIntentHandler().generate_smart_response()' id='140549220270992'>, 'success': True}.get"}, "teardown": {"duration": 0.5477659510000024, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestViewScheduleReal::test_view_schedule_commands", "lineno": 53, "outcome": "failed", "keywords": ["test_view_schedule_commands", "TestViewScheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0012908729999878688, "outcome": "passed"}, "call": {"duration": 0.004921658999990086, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 74, "message": "AssertionError: Failed to show schedule with: Show my schedule\nassert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 74, "message": "in test_view_schedule_commands"}], "log": [{"name": "refiloe", "msg": "Error getting user context: Mock.keys() returned a non-iterable (type Mock)", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.7445598, "msecs": 744.0, "relativeCreated": 22577.077388763428, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.745629, "msecs": 745.0, "relativeCreated": 22578.1466960907, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576899.7465715, "msecs": 746.0, "relativeCreated": 22579.089164733887, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}], "longrepr": "tests/test_phase3_scheduling.py:74: in test_view_schedule_commands\n    assert 'schedule' in message or 'booking' in message or \\\nE   AssertionError: Failed to show schedule with: Show my schedule\nE   assert ('schedule' in '' or 'booking' in '' or 'session' in '' or 'appointment' in '' or 'no bookings' in '' or 'free' in '')"}, "teardown": {"duration": 0.6791604740000139, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_book_session_natural_language", "lineno": 110, "outcome": "passed", "keywords": ["test_book_session_natural_language", "critical", "pytestmark", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.026028249000006554, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576900.4567108, "msecs": 456.0, "relativeCreated": 23289.228439331055, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.956768793000009, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7JffhDyeXTnWr7J7q'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7JffhDyeXTnWr7J7q'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576900.5654116, "msecs": 565.0, "relativeCreated": 23397.929191589355, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7Jq5wdS1t2hoqobBg'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7Jq5wdS1t2hoqobBg'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576900.8604994, "msecs": 860.0, "relativeCreated": 23693.01700592041, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7L7jBGttsSoe4v6hT'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7L7jBGttsSoe4v6hT'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.070632, "msecs": 70.0, "relativeCreated": 23903.149604797363, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7LzZPT2dqTMofskeM'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7LzZPT2dqTMofskeM'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.1087134, "msecs": 108.0, "relativeCreated": 23941.23101234436, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7M9jbC7P9mJEPVs6N'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7M9jbC7P9mJEPVs6N'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.1445487, "msecs": 144.0, "relativeCreated": 23977.06627845764, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MLQF6eMGCUNaiuHN'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MLQF6eMGCUNaiuHN'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.2026615, "msecs": 202.0, "relativeCreated": 24035.179138183594, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MZYLJvX4AQHhdu8x'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MZYLJvX4AQHhdu8x'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.2477264, "msecs": 247.0, "relativeCreated": 24080.244064331055, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MkTKaN74vKeuhWwJ'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MkTKaN74vKeuhWwJ'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.2851667, "msecs": 285.0, "relativeCreated": 24117.684364318848, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MvNVePBApL5YyDtq'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7MvNVePBApL5YyDtq'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.337283, "msecs": 337.0, "relativeCreated": 24169.800519943237, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7N82mxuQdHZBXtzEX'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7N82mxuQdHZBXtzEX'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.3734531, "msecs": 373.0, "relativeCreated": 24205.970764160156, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "AI intent understanding failed: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7NHhhZUW1by8hy7YK'}", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": "Traceback (most recent call last):\n  File \"/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/ai_intent_handler.py\", line 64, in understand_message\n    response = self.client.messages.create(\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_utils/_utils.py\", line 275, in wrapper\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/resources/messages.py\", line 888, in create\n    return self._post(\n           ^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1277, in post\n    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))\n                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 954, in request\n    return self._request(\n           ^^^^^^^^^^^^^^\n  File \"/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/anthropic/_base_client.py\", line 1058, in _request\n    raise self._make_status_error_from_response(err.response) from None\nanthropic.AuthenticationError: Error code: 401 - {'type': 'error', 'error': {'type': 'authentication_error', 'message': 'invalid x-api-key'}, 'request_id': 'req_011CTQA7NHhhZUW1by8hy7YK'}", "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576901.413216, "msecs": 413.0, "relativeCreated": 24245.733737945557, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.5162156999999752, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_time_formats", "lineno": 144, "outcome": "failed", "keywords": ["test_booking_time_formats", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.02331236500000955, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576901.9539316, "msecs": 953.0, "relativeCreated": 24786.449193954468, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.0010443150000014612, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_phase3_scheduling.py", "lineno": 168, "message": "AssertionError: Failed to validate time: 9am\nassert False == True"}, "traceback": [{"path": "tests/test_phase3_scheduling.py", "lineno": 168, "message": "in test_booking_time_formats"}], "longrepr": "tests/test_phase3_scheduling.py:168: in test_booking_time_formats\n    assert is_valid == True, f\"Failed to validate time: {time_format}\"\nE   AssertionError: Failed to validate time: 9am\nE   assert False == True"}, "teardown": {"duration": 0.7534906749999948, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookSessionsReal::test_booking_date_parsing", "lineno": 169, "outcome": "passed", "keywords": ["test_booking_date_parsing", "TestBookSessionsReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.023367470000010826, "outcome": "passed", "log": [{"name": "refiloe", "msg": "AI Intent Handler initialized with Claude", "args": null, "levelname": "INFO", "levelno": 20, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 21, "funcName": "log_info", "created": 1758576902.7387185, "msecs": 738.0, "relativeCreated": 25571.23613357544, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "call": {"duration": 0.0004458899999804089, "outcome": "passed"}, "teardown": {"duration": 0.4877680390000023, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_cancel_booking_variations", "lineno": 223, "outcome": "passed", "keywords": ["test_cancel_booking_variations", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0010397060000002512, "outcome": "passed"}, "call": {"duration": 0.013725949999980003, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2294574, "msecs": 229.0, "relativeCreated": 26061.97500228882, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.230082, "msecs": 230.0, "relativeCreated": 26062.599658966064, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.231194, "msecs": 231.0, "relativeCreated": 26063.711643218994, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2315214, "msecs": 231.0, "relativeCreated": 26064.0389919281, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2316885, "msecs": 231.0, "relativeCreated": 26064.20612335205, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2322285, "msecs": 232.0, "relativeCreated": 26064.746141433716, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2325447, "msecs": 232.0, "relativeCreated": 26065.062284469604, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2327259, "msecs": 232.0, "relativeCreated": 26065.24348258972, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2332404, "msecs": 233.0, "relativeCreated": 26065.757989883423, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2335527, "msecs": 233.0, "relativeCreated": 26066.070318222046, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.233709, "msecs": 233.0, "relativeCreated": 26066.226720809937, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2341695, "msecs": 234.0, "relativeCreated": 26066.68710708618, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2344997, "msecs": 234.0, "relativeCreated": 26067.017316818237, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2346532, "msecs": 234.0, "relativeCreated": 26067.17085838318, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2351172, "msecs": 235.0, "relativeCreated": 26067.63482093811, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2354422, "msecs": 235.0, "relativeCreated": 26067.959785461426, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2399147, "msecs": 239.0, "relativeCreated": 26072.432279586792, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2404256, "msecs": 240.0, "relativeCreated": 26072.943210601807, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2407472, "msecs": 240.0, "relativeCreated": 26073.264837265015, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2409022, "msecs": 240.0, "relativeCreated": 26073.41980934143, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2413971, "msecs": 241.0, "relativeCreated": 26073.914766311646, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.241718, "msecs": 241.0, "relativeCreated": 26074.235677719116, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.241871, "msecs": 241.0, "relativeCreated": 26074.3887424469, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.2423947, "msecs": 242.0, "relativeCreated": 26074.912309646606, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.6648589979999997, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestCancelRescheduleReal::test_reschedule_booking", "lineno": 248, "outcome": "passed", "keywords": ["test_reschedule_booking", "TestCancelRescheduleReal", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0011017109999897912, "outcome": "passed"}, "call": {"duration": 0.008630095000000892, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9098036, "msecs": 909.0, "relativeCreated": 26742.321252822876, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9127107, "msecs": 912.0, "relativeCreated": 26745.22829055786, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9136467, "msecs": 913.0, "relativeCreated": 26746.164321899414, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9139984, "msecs": 913.0, "relativeCreated": 26746.51598930359, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9141707, "msecs": 914.0, "relativeCreated": 26746.68836593628, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9146674, "msecs": 914.0, "relativeCreated": 26747.184991836548, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.915006, "msecs": 915.0, "relativeCreated": 26747.523546218872, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9151757, "msecs": 915.0, "relativeCreated": 26747.693300247192, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9156609, "msecs": 915.0, "relativeCreated": 26748.178482055664, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9159892, "msecs": 915.0, "relativeCreated": 26748.506784439087, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9161863, "msecs": 916.0, "relativeCreated": 26748.703956604004, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9166818, "msecs": 916.0, "relativeCreated": 26749.199390411377, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting user context: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9170213, "msecs": 917.0, "relativeCreated": 26749.538898468018, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error getting conversation history: 'Mock' object is not reversible", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.917194, "msecs": 917.0, "relativeCreated": 26749.711513519287, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}, {"name": "refiloe", "msg": "Error sending WhatsApp message: Object of type MagicMock is not JSON serializable", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576903.9176588, "msecs": 917.0, "relativeCreated": 26750.176429748535, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.8322372819999941, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_double_booking_prevention", "lineno": 283, "outcome": "passed", "keywords": ["test_double_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005232439999929284, "outcome": "passed"}, "call": {"duration": 0.001391931000000568, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576904.7525954, "msecs": 752.0, "relativeCreated": 27585.113048553467, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.5182943119999948, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_past_date_booking_prevention", "lineno": 313, "outcome": "passed", "keywords": ["test_past_date_booking_prevention", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0004534140000203024, "outcome": "passed"}, "call": {"duration": 0.0013035870000237537, "outcome": "passed", "log": [{"name": "refiloe", "msg": "Error checking booking conflict: object of type 'Mock' has no len()", "args": null, "levelname": "ERROR", "levelno": 40, "pathname": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/utils/logger.py", "filename": "logger.py", "module": "logger", "exc_info": null, "exc_text": null, "stack_info": null, "lineno": 25, "funcName": "log_error", "created": 1758576905.27325, "msecs": 273.0, "relativeCreated": 28105.767726898193, "thread": 140549554178944, "threadName": "MainThread", "processName": "MainProcess", "process": 2188}]}, "teardown": {"duration": 0.5168811849999884, "outcome": "passed"}}, {"nodeid": "tests/test_phase3_scheduling.py::TestBookingConflictsAndValidation::test_invalid_time_slots", "lineno": 334, "outcome": "passed", "keywords": ["test_invalid_time_slots", "TestBookingConflictsAndValidation", "test_phase3_scheduling.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0005920819999971627, "outcome": "passed"}, "call": {"duration": 0.00025751999999101827, "outcome": "passed"}, "teardown": {"duration": 0.4794575889999919, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_new_trainer_onboarding", "lineno": 227, "outcome": "passed", "keywords": ["test_new_trainer_onboarding", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00027656400001774273, "outcome": "passed"}, "call": {"duration": 0.004716518999998698, "outcome": "passed"}, "teardown": {"duration": 0.5970748659999856, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase1_UserRegistration::test_trainer_recognition", "lineno": 242, "outcome": "passed", "keywords": ["test_trainer_recognition", "TestPhase1_UserRegistration", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002943580000192014, "outcome": "passed"}, "call": {"duration": 0.011512510000017073, "outcome": "passed"}, "teardown": {"duration": 0.4841740990000005, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_add_client_variations", "lineno": 269, "outcome": "passed", "keywords": ["test_add_client_variations", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.000301030000002811, "outcome": "passed"}, "call": {"duration": 0.004280336999983092, "outcome": "passed"}, "teardown": {"duration": 0.5028781659999879, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_view_clients", "lineno": 278, "outcome": "passed", "keywords": ["test_view_clients", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002860419999990427, "outcome": "passed"}, "call": {"duration": 0.0026281519999997727, "outcome": "passed"}, "teardown": {"duration": 1.0188449730000002, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase2_ClientManagement::test_set_custom_pricing", "lineno": 286, "outcome": "passed", "keywords": ["test_set_custom_pricing", "TestPhase2_ClientManagement", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00030551900002251386, "outcome": "passed"}, "call": {"duration": 0.00471537900000385, "outcome": "passed"}, "teardown": {"duration": 0.6145184339999901, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_view_schedule", "lineno": 299, "outcome": "passed", "keywords": ["test_view_schedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031515699998863056, "outcome": "passed"}, "call": {"duration": 0.007753295000014759, "outcome": "passed"}, "teardown": {"duration": 0.5076409140000067, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_book_sessions", "lineno": 308, "outcome": "passed", "keywords": ["test_book_sessions", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003048270000078901, "outcome": "passed"}, "call": {"duration": 0.004887899999999945, "outcome": "passed"}, "teardown": {"duration": 0.6662862370000084, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase3_SchedulingBookings::test_cancel_reschedule", "lineno": 317, "outcome": "failed", "keywords": ["test_cancel_reschedule", "TestPhase3_SchedulingBookings", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00033304900000530324, "outcome": "passed"}, "call": {"duration": 0.005141843000018298, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 329, "message": "assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\n +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fd43a9cc1f0>()\n +    where <built-in method lower of str object at 0x7fd43a9cc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\n +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fd43a9cc1f0>()\n +    where <built-in method lower of str object at 0x7fd43a9cc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 329, "message": "in test_cancel_reschedule"}], "longrepr": "tests/test_refiloe_complete.py:329: in test_cancel_reschedule\n    assert \"reschedul\" in response['message'].lower() or \"moved\" in response['message'].lower()\nE   assert ('reschedul' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" or 'moved' in \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\")\nE    +  where \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fd43a9cc1f0>()\nE    +    where <built-in method lower of str object at 0x7fd43a9cc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower\nE    +  and   \"today's schedule:\\n9:00 am - sarah johnson\\n2:00 pm - john doe\" = <built-in method lower of str object at 0x7fd43a9cc1f0>()\nE    +    where <built-in method lower of str object at 0x7fd43a9cc1f0> = \"Today's schedule:\\n9:00 AM - Sarah Johnson\\n2:00 PM - John Doe\".lower"}, "teardown": {"duration": 0.4869161660000145, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase4_HabitTracking::test_setup_habits", "lineno": 334, "outcome": "passed", "keywords": ["test_setup_habits", "TestPhase4_HabitTracking", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029215400002158276, "outcome": "passed"}, "call": {"duration": 0.005755966999998918, "outcome": "passed"}, "teardown": {"duration": 0.6803769130000035, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase5_WorkoutsAssessments::test_send_workouts", "lineno": 347, "outcome": "passed", "keywords": ["test_send_workouts", "TestPhase5_WorkoutsAssessments", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003347640000015417, "outcome": "passed"}, "call": {"duration": 0.0050345020000008844, "outcome": "passed"}, "teardown": {"duration": 1.0277515900000083, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_request_payment", "lineno": 360, "outcome": "failed", "keywords": ["test_request_payment", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00035651400000347166, "outcome": "passed"}, "call": {"duration": 0.0029176319999919542, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 368, "message": "assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\n +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fd43a9299d0>()\n +    where <built-in method lower of str object at 0x7fd43a9299d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\n +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fd43a9299d0>()\n +    where <built-in method lower of str object at 0x7fd43a9299d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 368, "message": "in test_request_payment"}], "longrepr": "tests/test_refiloe_complete.py:368: in test_request_payment\n    assert \"payment\" in response['message'].lower() or \"invoice\" in response['message'].lower()\nE   assert ('payment' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" or 'invoice' in \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\")\nE    +  where \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fd43a9299d0>()\nE    +    where <built-in method lower of str object at 0x7fd43a9299d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower\nE    +  and   \"welcome to refiloe! i'm here to help you manage your personal training business. are you a trainer or a client?\" = <built-in method lower of str object at 0x7fd43a9299d0>()\nE    +    where <built-in method lower of str object at 0x7fd43a9299d0> = \"Welcome to Refiloe! I'm here to help you manage your personal training business. Are you a trainer or a client?\".lower"}, "teardown": {"duration": 0.8155552819999912, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase6_PaymentsRevenue::test_check_revenue", "lineno": 369, "outcome": "passed", "keywords": ["test_check_revenue", "TestPhase6_PaymentsRevenue", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002972630000215304, "outcome": "passed"}, "call": {"duration": 0.007769496000008758, "outcome": "passed"}, "teardown": {"duration": 0.5761583569999971, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_booking", "lineno": 381, "outcome": "passed", "keywords": ["test_client_booking", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0003029639999851952, "outcome": "passed"}, "call": {"duration": 0.004905552999986185, "outcome": "passed"}, "teardown": {"duration": 0.514783403999985, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase8_ClientFeatures::test_client_habit_logging", "lineno": 390, "outcome": "passed", "keywords": ["test_client_habit_logging", "TestPhase8_ClientFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002648429999965174, "outcome": "passed"}, "call": {"duration": 0.0027293820000124924, "outcome": "passed"}, "teardown": {"duration": 0.4941436099999805, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_natural_language_understanding", "lineno": 403, "outcome": "passed", "keywords": ["test_natural_language_understanding", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00031849300000885705, "outcome": "passed"}, "call": {"duration": 0.00453204800001572, "outcome": "passed"}, "teardown": {"duration": 0.8535389219999843, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestPhase10_AdvancedFeatures::test_error_handling", "lineno": 412, "outcome": "failed", "keywords": ["test_error_handling", "TestPhase10_AdvancedFeatures", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00034785799999781375, "outcome": "passed"}, "call": {"duration": 0.004691904999987173, "outcome": "failed", "crash": {"path": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/tests/test_refiloe_complete.py", "lineno": 424, "message": "assert False\n +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7fd42b766b20>)"}, "traceback": [{"path": "tests/test_refiloe_complete.py", "lineno": 424, "message": "in test_error_handling"}], "longrepr": "tests/test_refiloe_complete.py:424: in test_error_handling\n    assert any(word in response['message'].lower() for word in [\"past\", \"future\", \"cannot\"])\nE   assert False\nE    +  where False = any(<generator object TestPhase10_AdvancedFeatures.test_error_handling.<locals>.<genexpr> at 0x7fd42b766b20>)"}, "teardown": {"duration": 0.4833300599999859, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_trainer_registration_step_7_currency_parsing", "lineno": 433, "outcome": "passed", "keywords": ["test_trainer_registration_step_7_currency_parsing", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.0002921330000162925, "outcome": "passed"}, "call": {"duration": 0.0006496400000060021, "outcome": "passed"}, "teardown": {"duration": 0.6528468099999998, "outcome": "passed"}}, {"nodeid": "tests/test_refiloe_complete.py::TestCriticalBugs::test_ai_responds_naturally_not_rigid_commands", "lineno": 457, "outcome": "passed", "keywords": ["test_ai_responds_naturally_not_rigid_commands", "TestCriticalBugs", "test_refiloe_complete.py", "tests/__init__.py", "whatsapp-ai-assistant"], "setup": {"duration": 0.00029886600000850194, "outcome": "passed"}, "call": {"duration": 0.0027467959999967206, "outcome": "passed"}, "teardown": {"duration": 0.5663243889999876, "outcome": "passed"}}], "warnings": [{"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "The `update_forward_refs` method is deprecated; use `model_rebuild` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.11/migration/", "category": "PydanticDeprecatedSince20", "when": "collect", "filename": "/opt/hostedtoolcache/Python/3.11.13/x64/lib/python3.11/site-packages/gotrue/types.py", "lineno": 679}, {"message": "\nPyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),\n(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)\nbut was not found to be installed on your system.\nIf this would cause problems for you,\nplease provide us feedback at https://github.com/pandas-dev/pandas/issues/54466\n        ", "category": "DeprecationWarning", "when": "runtest", "filename": "/home/runner/work/whatsapp-ai-assistant/whatsapp-ai-assistant/services/analytics.py", "lineno": 7}]}